### ISSUE TITLE
geom_rasterann

### ISSUE THREAD

**Issue by Emaasit** [ropensci/plotly#401] opened 2016-01-16 22:47 UTC
I am trying to use plotly with ggmap (an extension of ggplot2 for maps). For example, when I execute this code, i get an error.
paris <- get_map(location = "paris")
m <- ggmap(paris, extent = "normal")
ggplotly(m)

Warning message:
In layer2traces(L, df, misc) :
  geom_rasterann has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment] 2016-01-18 18:30
Duplicate of #13

**Closed by cpsievert** 2016-01-18 18:30 UTC
