### ISSUE TITLE
Colour legend title cannot be changed

### ISSUE THREAD

**Issue by daattali** [ropensci/plotly#1411] opened 2018-11-15 23:31 UTC
Related to #1410 

The following code creates a scatterplot and tries to change the title of the colour legend

```
library(plotly)
df <- data.frame(x = 1:5, y = 1:5, colvariable = c(1,2,1,2,1))
plot_ly(df, x = ~x, y = ~y, color = ~colvariable ) %>%
    add_markers(marker = list(colorbar = list(title = "test")))
```

Rather than using "test" as the legend title, it says "colvariable".

![image](https://user-images.githubusercontent.com/952340/48588275-6ea13600-e904-11e8-96be-dc6e3a4576a7.png)

If all the colour values are identical (such as in #1410) then both "colvariable" and "test" are written and overlapping one another:

```
df <- data.frame(x = 1:5, y = 1:5, colvariable = c(1,1,1,1,1))
plot_ly(df, x = ~x, y = ~y, color = ~colvariable ) %>%
    add_markers(marker = list(colorbar = list(title = "test")))
```

![image](https://user-images.githubusercontent.com/952340/48588317-9ee8d480-e904-11e8-9209-dc8a0a48ad6e.png)

**Comment by cpsievert** [comment] 2018-11-15 23:35
Follow the advice in https://github.com/ropensci/plotly/issues/1410#issuecomment-439228753

Marking as duplicate of #1410

**Closed by cpsievert** 2018-11-15 23:35 UTC
