### ISSUE TITLE
List of shapes in layout cannot be updated 

### ISSUE THREAD

**Issue by susannvorberg** [ropensci/plotly#1669] opened 2019-12-06 09:18 UTC
When adding multiple shapes after another via `plotly::layout()`, only the first list of shapes is actually rendered in the plot. All the subsequent added shapes are lost.

Here is a code reproducing the issue: 
```r
p <- plot_ly(type="scatter", mode="markers+lines", x=c(1,2,3,4), y=c(2,3,4,5)) %>%
layout(shapes=list(list(type="rectangular", fillcolor="red", x0=0, x1=1, y0=0, y1=1)))

p <- p %>% 
layout(shapes=list(list(type="rectangular", fillcolor="blue", x0=0, x1=1, y0=1, y1=2)))
```

Only the red rectangle shows up in the plot:
![image](https://user-images.githubusercontent.com/3994406/70311298-afbaff80-1811-11ea-92cc-565b20568c88.png)

When printing the object with `str(p)` you can see that the object actually contains the two shape lists:
```
$ layoutAttrs:List of 2
  .. ..$ 2ea0215d1de9:List of 1
  .. .. ..$ shapes:List of 1
  .. .. .. ..$ :List of 6
  .. .. .. .. ..$ type     : chr "rectangular"
  .. .. .. .. ..$ fillcolor: chr "red"
  .. .. .. .. ..$ x0       : num 0
  .. .. .. .. ..$ x1       : num 1
  .. .. .. .. ..$ y0       : num 0
  .. .. .. .. ..$ y1       : num 1
  .. ..$ 2ea0215d1de9:List of 1
  .. .. ..$ shapes:List of 1
  .. .. .. ..$ :List of 6
  .. .. .. .. ..$ type     : chr "rectangular"
  .. .. .. .. ..$ fillcolor: chr "blue"
  .. .. .. .. ..$ x0       : num 0
  .. .. .. .. ..$ x1       : num 1
  .. .. .. .. ..$ y0       : num 1
  .. .. .. .. ..$ y1       : num 2
```

But when the plot is built, the two shape lists are not being merged (`str(plotly_build(p))`):

```
..$ layout     :List of 6
  .. ..$ margin    :List of 4
  .. .. ..$ b: num 40
  .. .. ..$ l: num 60
  .. .. ..$ t: num 25
  .. .. ..$ r: num 10
  .. ..$ shapes    :List of 1
  .. .. ..$ :List of 6
  .. .. .. ..$ type     : chr "rectangular"
  .. .. .. ..$ fillcolor: chr "red"
  .. .. .. ..$ x0       : num 0
  .. .. .. ..$ x1       : num 1
  .. .. .. ..$ y0       : num 0
  .. .. .. ..$ y1       : num 1
  .. ..$ xaxis     :List of 3
  .. .. ..$ domain    : num [1:2] 0 1
  .. .. ..$ automargin: logi TRUE
  .. .. ..$ title     : list()
  .. .. .. ..- attr(*, "class")= chr [1:2] "plotly_default" "list"
```

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
Plotly Version 4.9.0

**Comment by cpsievert** [comment] 2020-02-04 18:31
Thanks for the reprex. Duplicate of #1333

**Closed by cpsievert** 2020-02-04 18:31 UTC
