### ISSUE TITLE
ggplotly missing geom_GeomJoy

### ISSUE THREAD

**Issue by statquant** [ropensci/plotly#1093] opened 2017-08-02 20:23 UTC
I would love to see `joyplot` being implemented

```r
library(datasets)
library(ggjoy)
p = ggplot(iris, aes(x = Sepal.Length, y = Species)) + geom_joy(rel_min_height = 0.01)
library(plotly)
ggplotly(p)
Picking joint bandwidth of 0.181
Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomJoy() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```

**Comment by cpsievert** [comment] 2017-08-03 17:48
Duplicate of #348

**Closed by cpsievert** 2017-08-03 17:48 UTC
