### ISSUE TITLE
geom_text_repel not working in plotly....

### ISSUE THREAD

**Issue by rajan5660** [ropensci/plotly#1071] opened 2017-07-09 11:22 UTC
#load the data
data <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/school_earnings.csv")

#bubble chart with ggplot
g<-ggplot(data, aes(x = Women, y = Men, label =School ))+
  geom_point(aes(size =gap,alpha=0.5),shape=21,  stroke = 0.5,colour = "black")+
  geom_text_repel(size = 3,fontface = 'bold', color = 'black',segment.alpha = 0,segment.color = 'grey50' ) 

#plot output with ggplot
g
![image](https://user-images.githubusercontent.com/24388079/27993298-aff773cc-64c5-11e7-8079-60695267c714.png)

#using ggplolty to convert ggplot to plolty
ggplotly(g)

#plot output with ggplotly

![image](https://user-images.githubusercontent.com/24388079/27993317-381f7a7e-64c6-11e7-994e-490f10a9e662.png)

But this did  not print text of bubbles and give warning

Warning messages:
1: We recommend that you use the dev version of ggplot2 with `ggplotly()`
Install it with: `devtools::install_github('hadley/ggplot2')` 
2: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  **geom_GeomTextRepel() has yet to be implemented in plotly.**
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

![image](https://user-images.githubusercontent.com/24388079/27993334-a283c9f6-64c6-11e7-9fc8-c18e4f80dae2.png)

I am using ggplot to render the plot because i didn't found any way in plotly to repel the overlapping labels when the number of  bubbles are more on plot

**Comment by cpsievert** [comment] 2017-07-14 17:25
Duplicate of #566

**Closed by cpsievert** 2017-07-14 17:25 UTC
