### ISSUE TITLE
Multiple synchronized plots

### ISSUE THREAD

**Issue by TonyDIRL** [ropensci/plotly#298] opened 2015-11-13 16:55 UTC
Hi,

Really great library.

Is it possible to build multiple synchronized plots with plotly?

Specifically, I'm looking to emulate the behaviour of dygraphs:
https://rstudio.github.io/dygraphs/gallery-synchronization.html

In python its possible with subplots and the shared_yaxes / shared_xaxes params.
https://plot.ly/python/subplots/

Tried the following but no success:
```
subplot(
    plot_ly(economics, x = date, y = uempmed),
    plot_ly(economics, x = date, y = unemploy),
    margin = 0.05
) %>% layout(yaxis=list(shared_yaxes=TRUE))
```

Thank you

**Comment by cpsievert** [comment] 2015-11-14 22:32
Yea, this currently isn't easy to do with `subplot()`, but it's on my TODO list

**Comment by TonyDIRL** [comment] 2015-11-15 12:18
Thank you, that would be a really great addition.

**Comment by royr2** [comment] 2016-02-09 16:31
I am little late to this conversation but @TonyDIRL you could do something like this: 

```r
data(managers, package = "PerformanceAnalytics")
ds <- data.frame(dts = as.Date(zoo::index(managers)), 
                 t1 = as.numeric(managers[,1]),
                 t2 = as.numeric(managers[,3]),
                 t3 = as.numeric(managers[,4]))
head(ds)

ds %>% 
  plot_ly(x = dts, y = t1, type = "scatter", name = "Time Series 1") %>% 
  add_trace(x = dts, y = t2, yaxis = "y2", type = "scatter", name = "Time Series 2") %>% 
  add_trace(x = dts, y = t3, yaxis = "y3", type = "scatter", name = "Time Series 3") %>% 
  layout(title = "Connected Y-Axis plot", 
         yaxis = list(title = "Series1", domain = c(0, 0.32)),
         yaxis2 = list(title = "Series2",domain = c(0.33, 0.65)),
         yaxis3 = list(title = "Series3",domain = c(0.66, 1)))
```

I get something like this: [visit here for live version](https://plot.ly/~riddhiman/198/connected-y-axis-plot/)
![newplot](https://cloud.githubusercontent.com/assets/6601579/12922614/3535ef30-cf78-11e5-967c-7df702b3bb8d.png)

**Comment by TonyDIRL** [comment] 2016-02-09 23:47
Awesome, thank you

**Comment by cpsievert** [comment] 2016-05-16 05:20
Fixed via dd9a3fa

**Closed by cpsievert** 2016-05-16 05:20 UTC
Labels: enhancement

**Comment by lucasomigli** [comment] 2020-01-30 10:15
Any chance of doing the same thing in Python? I am trying to decode @royr2 to have a similar thing with two different charts.

**Comment by AkthemRehab** [comment] 2022-08-01 13:04
Hello, Thanks for a great package and a helpful thread. I used the subplot command to create three synchronized plots and it worked but I noticed a bug (or maybe I am doing something wrong, please enlighten me!). Whenever you set the nrows to 3 the second and third plots from the top do not synch with the first plot (my x-axis is a date axis and I have a second x axis which is a difftime column). I did a workarond by adding a 4th row and setting its height to 0. This revealed another issue that the 0 height of a plot in subplot does not hide it, but rather shows it in a very small size. Could you please help me resolve this/these issue(s)?

**Comment by AkthemRehab** [comment] 2022-08-01 15:28
> Hello, Thanks for a great package and a helpful thread. I used the subplot command to create three synchronized plots and it worked but I noticed a bug (or maybe I am doing something wrong, please enlighten me!). Whenever I set the nrows to 3 the second and third plots from the top do not synch with the first plot (my x-axis is a date axis and I have a second x axis which is a difftime column). I did a workarond by adding a 4th row and setting its height to 0 that interestingly worked! This revealed another issue that the 0 height of a plot in subplot does not hide it, but rather shows it in a very small size. Could you please help me resolve this/these issue(s)?

On trying 5 rows the issue resurfaced again. It seems the issue is appearing for me when I try subplot with 1 column and odd number rows. Thought to share this, maybe it helps investigating.
