### ISSUE TITLE
Plotly doesn't render geom_dotplot correctly

### ISSUE THREAD

**Issue by pelotom** [ropensci/plotly#1073] opened 2017-07-18 00:33 UTC
ggplot2:

```r
ggplot(mtcars, aes(hp)) + geom_dotplot(binwidth = 10, stackdir = 'center')
```

![dotplot](https://user-images.githubusercontent.com/128019/28295468-992670de-6b15-11e7-9d73-6d50ecf058da.png)

plotly:

```r
ggplotly(ggplot(mtcars, aes(hp)) + geom_dotplot(binwidth = 10, stackdir = 'center'))
```

![image](https://user-images.githubusercontent.com/128019/28295498-cd68f61e-6b15-11e7-9aca-880165cb6061.png)

**Comment by cpsievert** [comment] 2018-06-05 18:59
Duplicate of https://github.com/ropensci/plotly/issues/1213

**Closed by cpsievert** 2018-06-05 18:59 UTC
