### ISSUE TITLE
geom_GeomDensityRidges() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by apremgeorge** [ropensci/plotly#1513] opened 2019-04-09 01:11 UTC
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggridges)

df_train %>%
  gather(variable, value, -Target) %>%
  ggplot(aes(y = as.factor(variable), 
             fill = as.factor(Target), 
             x = percent_rank(value))) +
  geom_density_ridges()
```

Picking joint bandwidth of 0.0368
geom_GeomDensityRidges() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issuesgeom_GeomDensityRidges() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment] 2019-04-11 18:20
Duplicate of #566

**Closed by cpsievert** 2019-04-11 18:20 UTC

**Comment by jackpgao** [comment] 2019-04-26 07:09
+1

the ggridges plot is very useful.
