### ISSUE TITLE
Data with High Values

### ISSUE THREAD

**Issue by fabioand2k** [ropensci/plotly#429] opened 2016-01-26 23:36 UTC
Hello,

if i try to run ggplotly with large values (even with low number of observations)

when run, crash my machine. (i tried with another machine, and same problem)

code below:

library(ggplot2)
library(plotly)

employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(210000000, 234000000, 268000000)

employ.data <- data.frame(employee, salary)

p <- ggplot(employ.data ,aes(x=employee, y=salary)) +
  geom_bar(stat='identity', color="black") +
  scale_y_continuous(labels = function(x) format(x, big.mark = '.', decimal.mark = ',', scientific = FALSE)) 
ggplotly(p)

thanks

**Comment by cpsievert** [comment] 2016-01-27 17:24
We don't (yet) support specifying labels with a function. Closing since this is a duplicate of #185

**Closed by cpsievert** 2016-01-27 17:24 UTC

**Comment by fabioand2k** [comment] 2016-01-27 21:09
Hi Carlson,

the problem is not scale, sorry

the problem is big number.

library(ggplot2)
library(plotly)

employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(210000000, 234000000, 268000000)

employ.data <- data.frame(employee, salary)

p <- ggplot(employ.data ,aes(x=employee, y=salary)) +
geom_bar(stat='identity', color="black") 
ggplotly(p)


if you run this dataframe with 
salary <- c(210, 234, 268) = run instantly
and if you run with
salary <- c(210000000, 234000000, 268000000) = crash machine by high memory 

the problem is when you use "big numbers" 
thanks
