### ISSUE TITLE
Cannot using absolute path in orca

### ISSUE THREAD

**Issue by ygidtu** [ropensci/plotly#1630] opened 2019-09-29 06:47 UTC
---

Try to save plotly object to static file like, png or pdf. But `orca` cannot work with absolute path.

I guess when you call command line tools from R, it will add `$HOME` in front of `file path`, due to the `orca` function did not modify the input file path.

## Env 
- OS: 64bit Mac OS X 10.14.6 18G95
- Kernel: x86_64 Darwin 18.7.0
- Shell: zsh 5.3
- R: 3.6.0
- Rstudio: 1.2.1335
- plotly (R package): 4.9.0

## Example
```r
library(plotly)
library(dplyr)

p <- plot_ly(z = ~volcano) %>% add_surface()

orca(p, "surface-plot.png")   # ok

orca(p, "test/surface-plot.png")  # ok

orca(p, "/Users/<users>/test/surface-plot.png")  # failed
```

## Error
![image](https://user-images.githubusercontent.com/29178828/65827846-247c3580-e2c7-11e9-8c5c-e9321e10f535.png)

**Comment by cpsievert** [comment] 2019-11-06 19:27
Duplicate of #1310

**Closed by cpsievert** 2019-11-06 19:27 UTC
