### ISSUE TITLE
export function is producing pdf file with blank page

### ISSUE THREAD

**Issue by RNA-Ninja** [ropensci/plotly#1090] opened 2017-07-31 17:26 UTC
Saving a plot as **pdf** using **export** function is producing pdf file with 2 pages, first contains plot however second page is blank.
```r
library(plotly)
export(plot_ly(economics, x = ~date, y = ~pce), "plot.pdf")
```

**Comment by cpsievert** [comment] 2017-07-31 18:26
Duplicate of #1089

**Closed by cpsievert** 2017-07-31 18:26 UTC
