### ISSUE TITLE
ggmap

### ISSUE THREAD

**Issue by bendenis** [ropensci/plotly#788] opened 2016-11-06 03:16 UTC
nyc = get_map(location = "nyc")
ggmap(nyc)
ggplotly()

In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomRasterAnn() has yet to be implemented in plotly.

**Comment by cpsievert** [comment] 2016-11-11 23:18
duplicate of #348

**Closed by cpsievert** 2016-11-11 23:18 UTC
