### ISSUE TITLE
Setting "modeBarButtonsToAdd/Remove" to certain values causes no output with no error message

### ISSUE THREAD

**Issue by awgymer** [ropensci/plotly#1780] opened 2020-06-01 03:46 UTC
I started with a histogram trace which I removed the `lasso` and `box` select icons from the modebar successfully. Then I decided I wanted to make the `hoverinfo` toggleable like the graph from [this section of the docs](https://plotly.com/r/custom-buttons/#mapbox-access-token) and figured I could do `modeBarButtonsToAdd=c('toggleHover')` but this resulted in me getting a blank white "plot" in Rstudio. 

I figured I maybe misunderstood that option? 

I then made a scatter graph and discovered the same result if I tried just removing the `lasso/box` buttons too. 

    DT <- fread("
      posix_dt, sentiment, score
      2019-11-02 08:45:06,0.0000,2
      2019-11-02 08:45:07,0.0000,5
      2019-11-02 08:45:08,0.0201,4
      2019-11-02 08:45:14,0.2732,7
      2019-11-02 08:45:25,0.0000,3
      2019-11-02 08:45:35,0.3182,16
      2019-11-02 08:45:48,0.0000,3
      2019-11-02 08:45:53,-0.3582,6
      2019-11-02 08:46:00,0.4003,6
      2019-11-02 08:46:00,0.0000,7
      2019-11-02 08:46:04,0.0000,4
      2019-11-02 08:46:07,0.0000,2
      2019-11-02 08:46:16,0.4939,0
      2019-11-02 08:46:19,0.0000,2
      2019-11-02 08:46:32,-0.5267,2
      2019-11-02 08:46:49,0.2960,0
      2019-11-02 08:47:05,0.9753,7
      2019-11-02 08:47:05,0.0000,9
      2019-11-02 08:47:07,0.0000,3
      2019-11-02 08:47:10,-0.2960,9")
    DT[, posix_dt := as.POSIXct(posix_dt)]

    plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers") # Produces a plot
    
    # None of these work - produce empty white "plots"
     plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers")  %>% config(modeBarButtonsToRemove = c('select2d'))
    plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers")  %>% config(modeBarButtonsToRemove = c('lasso2d'))
    plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers")  %>% config(modeBarButtonsToRemove = c('hoverCompareCartesian'))
    plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers")  %>% config(modeBarButtonsToAdd = c('toggleHover'))

**Comment by cpsievert** [comment] 2020-06-01 14:55
Duplicate of https://github.com/ropensci/plotly/issues/1433

**Closed by cpsievert** 2020-06-01 14:55 UTC

**Comment by awgymer** [comment] 2020-06-01 16:59
I don't think that this is exactly the same issue, although I concede it appears it because I only used 1 option in each example. 

Although using a second value does fix some of them I still blank plots if some contain `toggleHover` or simple try using `modeBarButtonsToAdd`:
    
    pp <- plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers")
    
    # These DON'T work
    pp %>%  config(modeBarButtonsToAdd = c('select2d', 'lasso2d'), modeBarButtonsToRemove = c('toggleHover', 'zoom3d'))
    plot_ly(DT, x = ~posix_dt, y=~score, type="scatter", text=~sentiment, hoverinfo='text', mode="markers")  %>% config(modeBarButtonsToRemove = c('select2d', 'lasso2d'), modeBarButtonsToAdd = c('toggleHover', 'zoom3d'))
    pp %>%  config(modeBarButtonsToAdd = c('select2d', 'lasso2d'))
    pp %>% config(modeBarButtonsToAdd = c('toggleHover', 'zoom3d'))
    pp %>% config(modeBarButtonsToAdd = c('zoom4d', 'madeupparam'))
    
    # These work 
    pp %>% config(modeBarButtonsToRemove = c('toggleHover', 'zoom3d'))
    pp %>% config(modeBarButtonsToRemove = c('zoom4d', 'madeupparam'))
