### ISSUE TITLE
Bug of Scatter3D plots for only one point with multilevel?

### ISSUE THREAD

**Issue by BoyaoZhang** [ropensci/plotly#576] opened 2016-05-08 19:14 UTC
`plot_ly(x = iris[1,1], y = iris[1,2], z = iris[1,3], 
        type = "scatter3d", symbol = iris[1,5])`
![rplot](https://cloud.githubusercontent.com/assets/17792013/15099852/bef7d088-1561-11e6-99da-1896af3ddd30.png)

**Comment by kcf-jackson** [comment] 2016-05-08 21:03
I think the issue is that you supplied a factor to 'symbol'. Using characters string instead would fix the issue.
`plot_ly(x = iris[1,1], y = iris[1,2], z = iris[1,3], type = "scatter3d", symbol = as.character(iris[1,5]))`
![image](https://cloud.githubusercontent.com/assets/12783172/15100399/e5f93aa8-15b3-11e6-9daa-2da57ecc4f1f.png)

**Comment by BoyaoZhang** [comment] 2016-05-08 21:40
In fact I want to perform a machine learning algorithm on the iris data. According to the result, some points may be incorrect predicted. And I want to figure out this kind of points. For example, if the first data is miss-classified, I still want to have the same symbol shape, just want to change the color. Like this,

```
iris_without1 = iris[-1,]
iris_1 = iris[1,]
p = plot_ly(x = iris_without1[,1], y = iris_without1[,2], z = iris_without1[,3],
            type = "scatter3d", symbol = iris_without1[,5], marker = list(size = 3))
add_trace(p, x = iris_1[,1], y = iris_1[,2], z = iris_1[,3],
          type = "scatter3d", symbol = iris_1[,5], 
          marker = list(size = 3, color = "black"))

```

![rplot01](https://cloud.githubusercontent.com/assets/17792013/15100536/aa0cf514-1574-11e6-8416-d41bfb1f0a57.png)


You can see the square-shaped black point (miss-classified) in setosa group. This is in fact what I want in the end.

But I don't want to change it by giving a symbol name, I hope it perform automatically.

**Comment by kcf-jackson** [comment] 2016-05-09 02:17
If you want to remove the legend of the black dot, simply add "showlegend = FALSE" in the "add_trace" call.
```
iris_without1 = iris[-1,]
iris_1 = iris[1,]
p = plot_ly(x = iris_without1[,1], y = iris_without1[,2], z = iris_without1[,3],
            type = "scatter3d", symbol = as.character(iris_without1[,5]), marker = list(size = 3))
add_trace(p, x = iris_1[,1], y = iris_1[,2], z = iris_1[,3],
          type = "scatter3d", symbol = as.character(iris_1[,5]), 
          marker = list(size = 5, color = "black"), showlegend = FALSE)
```
![image](https://cloud.githubusercontent.com/assets/12783172/15102165/683e4e60-15df-11e6-86bf-4217e59fbe1c.png)

I think your questions are not development related, perhaps you could consider asking them in stackoverflow instead.

**Comment by BoyaoZhang** [comment] 2016-05-09 20:14
Sorry I asked here, but I still believe it must be a bug for single point with multi levels.
I think I chose a bad example, if I choose the 70th observation which belongs to `versicolor`. In the plot it should be a cross, but with `as.character` function it resolves as circle.

```
iris_without1 = iris[-70,]
iris_1 = iris[70,]
p = plot_ly(x = iris_without1[,1], y = iris_without1[,2], z = iris_without1[,3],
            type = "scatter3d", symbol = as.character(iris_without1[,5]), 
            marker = list(size = 3))
add_trace(p, x = iris_1[,1], y = iris_1[,2], z = iris_1[,3],
          type = "scatter3d", symbol = as.character(iris_1[,5]), 
          marker = list(size = 5, color = "black"), showlegend = FALSE)
```

![rplot03](https://cloud.githubusercontent.com/assets/17792013/15126575/e68f3128-1632-11e6-8f1d-17fd9890c501.png)

**Comment by kcf-jackson** [comment] 2016-05-10 02:23
As far as I see, plotly is doing exactly what you instructed it to do. Here is my understanding.
1. Plotly treats the data in 'add_trace' independently of the data you use in 'plot_ly', hence plotly produces two sets of symbols.
2. In 'add_trace', the data only has 1 point, the default 'circle' symbol is used. 

To solve your problem, I thought about using 'as.numeric' instead of 'as.character', but somehow plotly doesn't convert the numbers according to [https://plot.ly/r/reference/#box-marker-symbol](https://plot.ly/r/reference/#box-marker-symbol).
Though a simple fix can be found as follows:
```
data(iris)
symbol_3set <- c("circle", "cross", "square")

iris_without1 = iris[-70,]
iris_1 = iris[70,]
plot_ly(data = iris_without1, x = Sepal.Length, y = Sepal.Width, z = Petal.Length,
            type = "scatter3d", mode = "markers", color = Species,
            marker = list(size = 3, symbol = symbol_3set[as.numeric(Species)]))
add_trace(data = iris_1, x = Sepal.Length, y = Sepal.Width, z = Petal.Length,
          type = "scatter3d", mode = "markers", 
          marker = list(size = 5, color = "black", symbol = symbol_3set[as.numeric(Species)]), 
          showlegend = FALSE)

```
![image](https://cloud.githubusercontent.com/assets/12783172/15133705/b8ea5bbe-16a8-11e6-81c3-275ab0ec8054.png)

**Comment by BoyaoZhang** [comment] 2016-05-10 21:20
I must thank you for your patient. It goes very close to the end version which I want.
You know, iris is a very simple example. If I change the data set which has a lot of different levels, do you mean I should always type all the symbol names?
Why plotly couldn't convert the numeric symbol values? In [https://plot.ly/r/reference/#box-marker-symbol](url), the symbols are coded both for character and for numeric, aren't they?
In the following example, we can easily see the legend symbols are correct coded.

```
test = iris[c(1, 2, 51, 52, 101, 102),]
plot_ly(x = test$Sepal.Length, y = test$Sepal.Width, z = test$Petal.Length,
        type = "scatter3d", mode = "markers", color = test$Species,
        marker = list(symbol = c(1,1,2,2,3,3)))
```

![rplot](https://cloud.githubusercontent.com/assets/17792013/15162513/8fe050e2-1703-11e6-8a02-e6d2ab9f01ee.png)

**Comment by kcf-jackson** [comment] 2016-05-11 22:54
One uses colours if there are many levels as plotly only supports up to 8 symbols as far as I know.
And according to the documentation in the source code, 
```
#' @param symbol Either a variable name or a (discrete) vector to use for symbol encoding.
#' @param symbols A character vector of symbol types. Possible values:
#' 'dot', 'cross', 'diamond', 'square', 'triangle-down', 'triangle-left', 'triangle-right', 'triangle-up' 
```
there is no mention of allowing numeric encoding of symbols. The reference is possibly outdated.

**Comment by BoyaoZhang** [comment] 2016-05-12 01:21
I have run the following code to test these symbols, but any code couldn't generate the correct answer.

```
test = iris
test$Species = sample(1:8, 150, replace = T)
test$Species = as.factor(test$Species)
```

One can find in the legend labels that there are only 4 symbols
```
plot_ly(x = test$Sepal.Length, y = test$Sepal.Width, z = test$Petal.Length,
        type = "scatter3d", mode = "markers", symbol = test$Species)
```

![rplot](https://cloud.githubusercontent.com/assets/17792013/15201106/ae86c2e8-17ed-11e6-97c1-48dbbfef3409.png)

If I put the symbol parameter into the marker list, the symbols in the legend displays correctly, but none of the point are really with the symbol converted.
```
plot_ly(x = test$Sepal.Length, y = test$Sepal.Width, z = test$Petal.Length,
        type = "scatter3d", mode = "markers", color = test$Species,
        marker = list(symbol = as.numeric(test$Species)))
```
![rplot01](https://cloud.githubusercontent.com/assets/17792013/15201191/8f85c1a4-17ee-11e6-84b6-6f1bdc6fc52b.png)

Now I added the symbolset into the function. The output is almost same with the first plot but the incorrect legend labels.
```
symbolset = c('dot', 'cross', 'diamond', 'square', 'triangle-down', 'triangle-left', 'triangle-right', 'triangle-up')

plot_ly(x = test$Sepal.Length, y = test$Sepal.Width, z = test$Petal.Length,
        type = "scatter3d", mode = "markers",
        symbol = symbolset[as.numeric(test$Species)])
```

![rplot02](https://cloud.githubusercontent.com/assets/17792013/15201226/e44bd890-17ee-11e6-912a-71c1beff43e0.png)

Finally, the following code convert some points correctly, but some not. You can see, the triangle and dot symbols don't work. If I replace the symbol "dot" with the name "circle", than it works well for "circle". What is wrong with the outrageously symbols?

```
plot_ly(x = test$Sepal.Length, y = test$Sepal.Width, z = test$Petal.Length,
        type = "scatter3d", mode = "markers", color = test$Species,
        marker = list(symbol = symbolset[as.numeric(test$Species)]))
```
![rplot03](https://cloud.githubusercontent.com/assets/17792013/15201280/96462852-17ef-11e6-9f8b-1accbf313fb6.png)
![rplot04](https://cloud.githubusercontent.com/assets/17792013/15201297/c98f8640-17ef-11e6-83a1-b3de614dcf4d.png)

**Comment by cpsievert** [comment] 2016-05-18 00:00
pretty sure this is a duplicate of #577

**Closed by cpsievert** 2016-05-18 00:00 UTC
