### ISSUE TITLE
 Unable to render image with ggplotly

### ISSUE THREAD

**Issue by abiyug** [ropensci/plotly#1483] opened 2019-03-08 14:40 UTC
**The problem:**
ggplot2 can render images  with geom_images from the ggimage package.  ggplotly couldn't render the images because, as the warning message states,  the "geom_GeoImage()" has yet to be implemented. Here is the full message:

```
geom_GeomImage() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```

**The code:**
```r
# load lib
library(plotly)
library(ggplot2)
library(ggimage)

# play by play data
url.18 <- getURL("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/play_by_play_data/regular_season/reg_pbp_2018.csv")
pbp <- read.csv(text = url.18)
scrimmage.plays <- pbp %>% 
                                 filter(play_type == "pass"|play_type == "run")
# logo images/url
url.logo <- getURL("https://raw.githubusercontent.com/statsbylopez/BlogPosts/master/nfl_teamlogos.csv")
df.logos <- read.csv(text = url.logo)

# merge 
scrimmage.plays.summary <- scrimmage.plays.summary %>% 
                                                left_join(df.logos, by = c("posteam" = "team_code"))

# Viz
gg <- ggplot(scrimmage.plays.summary, aes(run, pass)) + 
               geom_image(aes(image = url), size = 0.05)
# plotly
ggplotly(gg)
```
**Request:**
1/  geom_image support for ploltly
2/  Native support for rendering images with url.png 

**SessoinInfo:**
R version 3.5.2 (2018-12-20)
plotly_4.8.0
ggimage_0.2.0
ggplot2_3.1.0

**Comment by cpsievert** [comment] 2019-03-12 23:12
Duplicate of #566.

In the meantime, you add images using `layout()` https://linking.plotly-r.com/embedding-images.html

**Closed by cpsievert** 2019-03-12 23:12 UTC
