### ISSUE TITLE
plotlyProxyInvoke("relayout", images=list(source=raster2uri

### ISSUE THREAD

**Issue by tjmcdono** [ropensci/plotly#1487] opened 2019-03-12 23:42 UTC
---

How to plotlyProxyInvoke("relayout", an image in plot please?
For example, an image stretched to fit the x,y field of view.
Aiming to update with images = list(source=raster2uri(obj).

```r
      plotlyProxy("plot4", session) %>%
        plotlyProxyInvoke("relayout", list(
          
          #images = list(
            source = raster2uri(a5), # converts a raster object to a data URI.
            xref = "x", yref = "y", x = 0, y = m1, sizex = 800, sizey = m2-m1,
            sizing = "stretch", xanchor = "left", yanchor = "bottom"
          #)
          # xaxis = list(range = c(m1,m2))
          # 
          ))
```

**Comment by cpsievert** [comment] 2019-03-13 14:20
Closing since this is question, not a bug report.

> Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the community forum <http://community.plot.ly/c/api/r> or stackoverflow <http://stackoverflow.com>.

**Closed by cpsievert** 2019-03-13 14:20 UTC

**Comment by tjmcdono** [comment] 2019-03-13 14:25
Update, 
Currently patching together a solution to hopefully pass jsonlite::toJSON(raster2uri(a5)) to session$sendCustomMessage. Then, ideally, set plot4.layout.images[0].source to 'message' in Shiny.addCustomMessageHandler.
