### ISSUE TITLE
geom_GeomLabel() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by ialibi** [ropensci/plotly#1616] opened 2019-09-16 22:30 UTC
I use to geom_segment combining with Shiny to create interactive plot.
It would be nice to see geom_label() supported by plotly.
So each segment can label with data information. 
Below is the example codes:
a <- ggplot(data=ae_sel()) +
        geom_segment(aes(x=AESTDY, xend=AEENDY, y=AEDECOD, yend=AEDECOD, fill=AETOXGR, color=AETOXGR), size=2) +
        geom_label(aes(x=AESTDY, y=AEENDY,  label = USUBJID)) +
        theme_bw() + 
        theme(panel.grid.major = element_blank(),
              plot.title = element_text(face="bold.italic",colour="#000066", size=14),
              axis.title.x=element_text(face="bold", colour="#000066", size=12),
              axis.text.y=element_blank(),  
              legend.title=element_text(size=9, color="#000066"), 
              legend.text=element_text(size=5))
    )
  })

**Comment by cpsievert** [comment] 2019-09-23 14:29
Duplicate of #348

**Closed by cpsievert** 2019-09-23 14:29 UTC
