### ISSUE TITLE
Implement geom_text_repel

### ISSUE THREAD

**Issue by antoniomolins** [ropensci/plotly#550] opened 2016-04-15 23:00 UTC
ggplotly doesn't currently have support for `geom_text_repel`, a very useful labeling package you can find [here](https://github.com/slowkow/ggrepel). It would be a great addition for busy plots where the hover doesn't cut it.

**Comment by cpsievert** [comment] 2016-04-28 12:08
Duplicate of #566

**Closed by cpsievert** 2016-04-28 12:08 UTC
