### ISSUE TITLE
Could not generate a 3D scatterplot in RStudio 

### ISSUE THREAD

**Issue by SpinoPi** [ropensci/plotly#1078] opened 2017-07-21 05:56 UTC
I could not generate a 3D scatterplot in RStudio. The R code is:
```r
data(mpg)
plot_ly(mpg, x = ~cty,y = ~hwy, z = ~cyl) %>%
add_markers(color = ~cyl)
```
 I just copy this sample from [ https://plotly-book.cpsievert.me/scatter-traces.html
](url)

Which just generated an image like this:
![capture](https://user-images.githubusercontent.com/18522943/28450787-2a3bf478-6e1c-11e7-9746-a93b9d9e538b.JPG)
Please help me solve this problem. Thank you very much!

**Comment by cpsievert** [comment] 2017-07-21 14:25
Duplicate of #1055

**Closed by cpsievert** 2017-07-21 14:25 UTC
