### ISSUE TITLE
geom_GeomCustomAnn() has yet to be implemented in plotly.

### ISSUE THREAD

**Issue by mbaxaci2** [ropensci/plotly#1878] opened 2020-11-05 17:13 UTC
When using the ggsoccer package to make plots. The following code:

library(ggsoccer)
library(ggplot2)
library(plotly)

g <- ggplot() +
      annotate_pitch()

ggplotly(g)

Results in these warnings:

Warning messages:
1: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomCustomAnn() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
2: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomCustomAnn() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
3: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomCustomAnn() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

I believe the issues are caused by the semi-circle in the middle, and the two arcs either side.

**Comment by cpsievert** [comment] 2020-12-08 23:26
Duplicate of #566

**Closed by cpsievert** 2020-12-08 23:26 UTC
