### ISSUE TITLE
Firefox but not Chrome performance affected by tick labels, orientation

### ISSUE THREAD

**Issue by jchrom** [ropensci/plotly#1505] opened 2019-03-30 13:06 UTC
I'm utterly baffled by this.

The below `html_document` causes Firefox to take 20+ seconds to display, and complain that the page is slowing the browser down:

```
library(plotly)
dat = data.frame(
  y = c(
    "All",
    "Contractor",
    "AU staff",
    "International staff",
    "National staff",
    "Other",
    "Student",
    "Teaching staff"
  ),
  x = 1
)
plot_ly(dat, x = ~x, y = ~y, type = "bar")
```
Memory usage is sky high as well. However, if I change the values on the y axis as below, the page load becomes instantaneous, and costs next to nothing in terms of memory:

```
dat = data.frame(
  y = c(
    "...",
    "..........",
    ".. .....",
    "............. .....",
    "........ .....",
    ".....",
    ".......",
    "........ ....."
  ),
  x = 1
)
```

Why should this matter? They are the same length, just dots instead of letters! Also, note that if I use the original data, and only switch the axes, the performance is not affected (i.e. it is good):

```
plot_ly(dat, x = ~y, y = ~x, type = "bar")
```
I'm using `html_document` output with `self_contained: false` (but the behaviour is the same whether it is set to `true` or `false`). See the output HTML file [here](https://drive.google.com/file/d/18GZ2B5Ki8vxjs89RDtzYyyb8NPknDD6F/view?usp=sharing).

R version 3.4.4
plotly 4.8.0

**Comment by cpsievert** [comment] 2019-04-01 15:44
I can't reproduce the issues you're seeing. I'd be useful to know the version of Firefox and pandoc.

**Comment by jchrom** [comment] 2019-04-02 07:26
I have since consistently reproduced this on one machine but failed to reproduce on two others, using:

* FF 66.0.2 & Ubuntu 18.04 on all machines
* Pandoc, tried 3 versions 1.9, 2.3, 2.7.1 on each machine

The one that is failing is booting from an SSD, but I cannot imagine this being a factor. If you have any ideas as to what else I can investigate, please share. Otherwise I'm ok with closing this as it looks like a problem with my local setup.

**Comment by cpsievert** [comment] 2019-04-02 14:47
Interesting, if the SSD is the only difference, I might close. I have a feeling this is more of a rmarkdown issue anyway, especially if the plotly plot renders fine outside of rmarkdown (have you tried a similar doc with some other htmlwidget like leaflet?)

**Comment by trafficonese** [comment] 2019-04-04 14:30
I am also not able to reproduce that problem.
If you pack your code in a shinyApp and open it in Firefox, it renders also almost instantaneous.

**Comment by cpsievert** [comment] 2019-04-04 20:47
Closing as I don't think I'll be able to reproduce. Feel free to reopen if you're able to narrow down the culprit.

**Closed by cpsievert** 2019-04-04 20:47 UTC
