### ISSUE TITLE
Warning message: `group_by_()` is deprecated as of dplyr 0.7.0.

### ISSUE THREAD

**Issue by mdancho84** [ropensci/plotly#1786] opened 2020-06-05 19:19 UTC
I'm getting warnings from `ggplotly()`. Upon inspection, it looks like https://github.com/ropensci/plotly/blob/master/R/ggplotly.R uses `dplyr::group_by_()`, which is deprecated. 

# Solutions

Problem:
![image](https://user-images.githubusercontent.com/13734662/83914488-4fb10180-a73f-11ea-8d2b-b7af2217ba49.png)
The fix is to use something like:

Fix:
```
dplyr::group_by(layout$layout, rlang::sym("xaxis"))
```

Problem
![image](https://user-images.githubusercontent.com/13734662/83914703-c221e180-a73f-11ea-8607-fb6e1913ccdf.png)

Fix:
```
dplyr::group_by(x, rlang::sym(y[["group"]]))
```

**Comment by gustavdelius** [comment] 2020-06-08 08:24
Same issue as #1783

**Comment by cpsievert** [comment] 2020-06-11 15:14
Closing since this is a duplicate of #1783

**Closed by cpsievert** 2020-06-11 15:14 UTC
