### ISSUE TITLE
Upgrade plotly.js to 1.5.n <--> xaxis : automargin causes infinite loop

### ISSUE THREAD

**Issue by bjornol** [ropensci/plotly#1642] opened 2019-10-18 13:41 UTC
Is it in the plans to upgrade plotly.js to 1.5 any time soon?
I’m having trouble as described in the issues below in regard to plotly causes
infinite lop (xaxis : automargin causes infinite loop) 

https://github.com/plotly/plotly.js/issues/4028
https://github.com/plotly/plotly.js/pull/4216

Changes in the plotly.js >= 1.5.0 releases fix these issues.

**Comment by cpsievert** [comment] 2019-10-23 15:02
Yes, there is a WIP in #1643 

Closing as this is a duplicate of #1643

**Closed by cpsievert** 2019-10-23 15:02 UTC
