### ISSUE TITLE
Subplots still not working in R

### ISSUE THREAD

**Issue by NicolasWoloszko** [ropensci/plotly#819] opened 2016-11-30 14:18 UTC
This R code : 
p11 <- plot_ly(results, x = ~N, y = ~T, z=  ~FEVD) %>% add_markers(color=~FEVD)
p10 <- plot_ly(results, x = ~N, y = ~T, z=  ~UFE) %>% add_markers(color=~UFE)

subplot(p11,p10, nrows = 2)
returns a single plot, instead of two subplots.

**Comment by cpsievert** [comment] 2016-11-30 16:22
Duplicate of #711

**Closed by cpsievert** 2016-11-30 16:22 UTC
