### ISSUE TITLE
ggplotly for geom_bar turns negative values into positive

### ISSUE THREAD

**Issue by MarkEdmondson1234** [ropensci/plotly#616] opened 2016-05-31 13:27 UTC
Negative values become positive:

```r
library(ggplot2)
library(plotly)
d <- data.frame(s = c("a","b","c"), v = c(-1,-2,3))
hh <- ggplot(d, aes(x = s, y = v))
hh <- hh + geom_bar(stat = "identity")
hh
```
![screen shot 2016-05-31 at 15 24 12](https://cloud.githubusercontent.com/assets/3155884/15675796/e128293e-2743-11e6-8de1-59c5a69246a2.png)

```r
plotly::ggplotly(hh)
```
![screen shot 2016-05-31 at 15 24 23](https://cloud.githubusercontent.com/assets/3155884/15675802/e4af4132-2743-11e6-957e-a7972d7c5fdd.png)

```r
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```

### Versions

plotly_3.6.0
ggplot2_2.1.0

**Comment by timelyportfolio** [comment] 2016-05-31 13:30
@MarkEdmondson1234,  thanks for reporting.  This is a duplicate of #560, so we will track progress there.  Unfortunately, there is not a workaround at this moment.

**Closed by timelyportfolio** 2016-05-31 13:30 UTC

**Comment by timelyportfolio** [comment] 2016-06-14 21:01
@MarkEdmondson1234 see https://github.com/ropensci/plotly/issues/560#issuecomment-226013608 for how to accomplish with just plain `plot_ly`
