### ISSUE TITLE
Some hovertexts show only one character

### ISSUE THREAD

**Issue by brainprint** [ropensci/plotly#1080] opened 2017-07-23 10:42 UTC
Hi,

I have created a 3D chart, using R, but some hovertexts show **only one character**, but the majority is correct (6 full lines with the correct text).

```
nullLabel <- list(title = "", showticklabels = FALSE)

p <- plot_ly(data = testDF, x = ~fromDF, y = ~toDF, z = ~dateDF, color = ~threadDF, colors = rainbow(length(unique(testDF$threadDF))), size = ~attDF, marker = list(symbol = "circle", sizemode = "diameter", showscale = FALSE), sizes = c(10, 50), hoverinfo = "text", text = ~paste0("From: ", fromDF, "\nTo: ", toDF, "\ncc: ", ccDF, "\nSubject: ", subjectDF, "\nDate: ", dateDF, "\nAttachments: ", attDF)) %>% layout(showlegend = FALSE, title = "Some Title", scene = list(xaxis = nullLabel, yaxis = nullLabel, zaxis = nullLabel)) %>% add_markers()
print(p)

```
And here an example of a wrong hovertext. The text inside the data frame is correct.

<https://cdn-standard.discourse.org/uploads/plot/original/2X/9/95cc4fe92b6c30cedcaa4088b8c6a80fbb005033.jpg>

I am aware that before it was common to use “<\br>” but it doesn’t work anymore. Instead I have to use “\n”.

I am using macOS 10.12.5, RStudio (but same result using pure R), R Version 3.4.1 and plotly package 4.7.0.9000.

Any help would be appreciated. Thank you.

**Comment by brainprint** [comment] 2017-07-23 18:09
Hoping it could help, I am attaching the RData file with the testDF object.
[testDF.RData.zip](https://github.com/ropensci/plotly/files/1168282/testDF.RData.zip)

**Comment by cpsievert** [comment] 2018-06-05 18:08
Duplicate of https://github.com/ropensci/plotly/issues/1125

**Closed by cpsievert** 2018-06-05 18:08 UTC
