### ISSUE TITLE
Row order in data.frame not maintained  in R Plotly chart with color variable

### ISSUE THREAD

**Issue by pssguy** [ropensci/plotly#673] opened 2016-08-09 17:44 UTC
``` 
df <- structure(list(count = c(8, 3, 5, 9), names = c("I", "want", 
    "this", "order"), type = c("H", "A", "H", "A")), .Names = c("count", 
    "names", "type"), row.names = c(NA, -4L), class = "data.frame")

    plot_ly(data=df,x=names,y=count,type="bar",
       color = type)
 ```
![rplot](https://cloud.githubusercontent.com/assets/2775918/17526752/6daef850-5e1d-11e6-9770-9e15eb98af35.png)

The issue is not confined to bar charts
The issue is solved by adding a layer
```
layout(xaxis = list(categoryarray = names, categoryorder = "array"))
```
but from the documentation, shouldn't the the default should be  categoryorder = "trace" which orders them as per data.frame?

**Comment by cpsievert** [comment] 2016-08-10 18:03
Duplicate of #578

**Closed by cpsievert** 2016-08-10 18:03 UTC
