### ISSUE TITLE
ggplotly does not work for dotplots

### ISSUE THREAD

**Issue by stla** [ropensci/plotly#1129] opened 2017-09-30 12:11 UTC
Hello, 

```
library(plotly)
gg <- ggplot(iris, aes(x=Species, y=Petal.Width)) +
  geom_dotplot(binwidth = 0.1, binaxis="y", stackdir = "center")
ggplotly(gg)
```

Unexpected output:

![bug_dotplotly](https://user-images.githubusercontent.com/4466543/31045675-1efcfcc4-a5e9-11e7-8629-b39e6fbb55a9.png)

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=French_Belgium.1252  LC_CTYPE=French_Belgium.1252   
[3] LC_MONETARY=French_Belgium.1252 LC_NUMERIC=C                   
[5] LC_TIME=French_Belgium.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] markdown_0.8       knitr_1.17         purrr_0.2.3        shinythemes_1.1.1 
[5] shinyjs_0.9.1      plotly_4.7.1       ggthemes_3.4.0     ggplot2_2.2.1.9000
[9] shiny_1.0.5       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      plyr_1.8.4        bindr_0.1         tools_3.3.3      
 [5] digest_0.6.12     evaluate_0.10.1   jsonlite_1.5      tibble_1.3.4     
 [9] gtable_0.2.0      viridisLite_0.2.0 pkgconfig_2.0.1   rlang_0.1.2      
[13] crosstalk_1.0.0   yaml_2.1.14       bindrcpp_0.2      stringr_1.2.0    
[17] dplyr_0.7.2       httr_1.3.1        sourcetools_0.1.6 htmlwidgets_0.9  
[21] grid_3.3.3        glue_1.1.1        data.table_1.10.4 R6_2.2.2         
[25] reshape2_1.4.2    tidyr_0.7.0       magrittr_1.5      MASS_7.3-47      
[29] scales_0.5.0      htmltools_0.3.6   assertthat_0.2.0  mime_0.5         
[33] xtable_1.8-2      colorspace_1.3-2  httpuv_1.3.5      labeling_0.3     
[37] stringi_1.1.5     miniUI_0.1.1      lazyeval_0.2.0    munsell_0.4.3    
```

**Comment by cpsievert** [comment] 2018-06-05 18:59
Duplicate of https://github.com/ropensci/plotly/issues/1213

**Closed by cpsievert** 2018-06-05 18:59 UTC
