### ISSUE TITLE
Surface plot axis title broken

### ISSUE THREAD

**Issue by quartox** [ropensci/plotly#393] opened 2016-01-13 17:57 UTC
When using the surface plot, I am unable to change the axis labels using layout (taken from the documentation from https://plot.ly/r/reference/#layout-scene-xaxis).

```
PlotlySurface <- function(xAxis,yAxis,marginalEffect,variableNames) {
  axesNames <- lapply(1:2, function(index) {
    list(title = variableNames[index])
  })
  plot_ly(x=xAxis,y=yAxis,z=marginalEffect,type='surface') %>%
    layout(xaxis = axesNames[[1]], yaxis = axesNames[[2]])
}
```
This does change the axis names from default (the x axis would be labeled "xAxis" otherwise) but does not give the names that I specify from "variableNames" (which is a character vector with the names of the variables).

![capture](https://cloud.githubusercontent.com/assets/8449196/12302736/9b722000-b9db-11e5-8770-b57f7660743e.PNG)

I have included my devtools session info below.

```
devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.97.551)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2016-01-13                  

Packages ----------------------------------------------------------------------------------------------------------------------
 package     * version  date       source        
 base64enc     0.1-3    2015-07-28 CRAN (R 3.2.2)
 colorspace    1.2-6    2015-03-11 CRAN (R 3.2.2)
 devtools      1.9.1    2015-09-11 CRAN (R 3.2.2)
 digest        0.6.8    2014-12-31 CRAN (R 3.2.2)
 gbm         * 2.1.1    2015-03-11 CRAN (R 3.2.2)
 ggplot2     * 2.0.0    2015-12-18 CRAN (R 3.2.3)
 gridExtra     2.0.0    2015-07-14 CRAN (R 3.2.2)
 gtable        0.1.2    2012-12-05 CRAN (R 3.2.2)
 htmltools     0.3      2015-12-29 CRAN (R 3.2.3)
 htmlwidgets   0.5      2015-06-21 CRAN (R 3.2.3)
 httr          1.0.0    2015-06-25 CRAN (R 3.2.2)
 jsonlite    * 0.9.16   2015-04-11 CRAN (R 3.2.2)
 lattice     * 0.20-33  2015-07-14 CRAN (R 3.2.2)
 magrittr      1.5      2014-11-22 CRAN (R 3.2.2)
 memoise       0.2.1    2014-04-22 CRAN (R 3.2.2)
 munsell       0.4.2    2013-07-11 CRAN (R 3.2.2)
 plotly      * 2.0.16   2015-12-20 CRAN (R 3.2.3)
 plyr          1.8.3    2015-06-12 CRAN (R 3.2.2)
 R6            2.1.1    2015-08-19 CRAN (R 3.2.2)
 Rcpp          0.12.1   2015-09-10 CRAN (R 3.2.2)
 rstudio       0.97.551 2015-08-26 local         
 rstudioapi    0.3.1    2015-04-07 CRAN (R 3.2.2)
 scales        0.3.0    2015-08-25 CRAN (R 3.2.2)
 stringi       0.5-5    2015-06-29 CRAN (R 3.2.2)
 stringr       1.0.0    2015-04-30 CRAN (R 3.2.2)
 survival    * 2.38-3   2015-07-02 CRAN (R 3.2.2)
 viridis       0.3.2    2015-12-31 CRAN (R 3.2.3)
 yaml          2.1.13   2014-06-12 CRAN (R 3.2.3)
```

**Comment by cpsievert** [comment] 2016-01-13 20:43
Bug confirmed, thanks. Here is a minimal example:

```r
plot_ly(z = volcano, type = "surface") %>%
  layout(xaxis = list(title = "x2"))
```

**Comment by etpinard** [comment] 2016-01-13 20:47
@cpsievert axis titles (and all other axis attributes) need to be nested into `layout.scene` in 3d plots.

**Comment by cpsievert** [comment] 2016-01-13 20:51
@etpinard just realized that, but you beat me to it. Closing since this works:

```r
plot_ly(z = volcano, type = "surface") %>%
  layout(scene = list(xaxis = list(title = "x2")))
```

**Comment by quartox** [comment] 2016-01-13 21:56
Your example works for me, but it will not replace labels when you specify the axis values.

Some examples:
```
plot_ly(z = volcano, type = "surface") %>%
  layout(scene = list(zaxis = list(title = "z2")))

plot_ly(x=1:87,y=1:61,z=volcano,type="surface") %>%
  layout(scene=list(xaxis=list(title='x2')))
```
The first figure still has z-axis labeled as 'volcano' and the second figure has x-axis labeled as '1:87'.

**Closed** 2016-01-18 15:48 UTC
Labels: bug
