### ISSUE TITLE
support for ggraph

### ISSUE THREAD

**Issue by JannikVindeloev** [ropensci/plotly#1052] opened 2017-06-20 08:50 UTC
Could you provide plotly support for the ggraph package, an extension of the grammer of graphics for networks: https://github.com/thomasp85/ggraph

```r
library(tidyverse)
library(igraph)
library(ggraph)
library(plotly)

nodes <- LETTERS[1:10] %>%
   tibble(name = ., x = seq(1:10), y = seq(1:10))

edges <- tribble(
  ~from, ~to,
  "A", "B",
  "C", "E",
  "C", "F",
  "F", "G",
  "J", "I"
)

g <- graph_from_data_frame(edges, vertices = nodes)

p <- g %>% ggraph(layout = "manual", node.positions = nodes)+
  geom_edge_link()+
  geom_node_label(aes(label = name))

ggplotly(p) # does not work! 
```

**Comment by cpsievert** [comment] 2017-06-20 15:34
Duplicate of #566

**Closed by cpsievert** 2017-06-20 15:34 UTC
