### ISSUE TITLE
geom_ma not implemented

### ISSUE THREAD

**Issue by vikram-rawat** [ropensci/plotly#1258] opened 2018-05-17 09:23 UTC
I get this error when I try to run a plot from tidyquant package.

```
Warning in geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomMA() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "26e4572a4a1f"; Shiny doesn't use them
```

Please implement it if you can.

**Comment by cpsievert** [comment] 2018-05-17 13:52
Duplicate of #566

**Closed by cpsievert** 2018-05-17 13:52 UTC

**Comment by vikram-rawat** [comment] 2018-05-17 14:11
I think you are pressed for a lot of geom types and it might take a while.
But for the time being can you tell me please how should I do it the plotly
way.

Please need help.

गुरु, 17 मई 2018, 7:22 pm को Carson Sievert <notifications@github.com> ने
लिखा:
