### ISSUE TITLE
geom_GeomEdgeParallelPath

### ISSUE THREAD

**Issue by GautierStauffer** [ropensci/plotly#1766] opened 2020-05-14 11:55 UTC
Hi,

I am not sure in which detail I should go here (it is the first time I report an issue) but I am using ggraph to plot some networks and it would be awesome if I could use plotly to make the graph interactive ! So as suggested in the warnings (see below) resulting from typing ggplotly(g) where g is the graph I created (using ggraph and geom_edge_parallel()), I open an issue here.

Thanks in anticipation !

Gautier

--

library(tidygraph)
library(ggraph)
library(plotly)

edges<- data.frame(
  from=c("A", "A", "B", "D", "C", "D", "E", "B", "C", "D", "K", "A", "M"),
  to=c("B", "E", "F", "A", "C", "A", "B", "Z", "A", "C", "A", "B", "K")
)
V=union(edges$from,edges$to)
nodes=data.frame(id=V)

graph <- tbl_graph(nodes = nodes, edges = edges, directed = FALSE)

g=ggraph(graph) + geom_edge_parallel() + geom_node_point() + theme_graph() + geom_node_text(aes(label = id), repel = TRUE)

ggplotly(g)

--- 

Warning messages:
1: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomEdgePath() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
2: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomTextRepel() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment] 2020-05-19 20:46
There is a wip attempt for **ggraph** support that you can try here...https://github.com/ropensci/plotly/pull/1326

Marking as a duplicate of #566 which I'll update if and when #1326 lands

**Closed by cpsievert** 2020-05-19 20:46 UTC
