### ISSUE TITLE
Unable to export graph to pdf (Error 402 received)

### ISSUE THREAD

**Issue by flop71** [ropensci/plotly#873] opened 2017-02-06 22:35 UTC
Hi

I'm using the latest drop of plotly (pulled 5th of Feb)  from github, while i can export a png successful via command line I get an error trying to export as pdf:

If I run

plotly_IMAGE(field.defects.df.weekly.pc.bar, width = 1000, height = 400, format = "pdf", scale = 2,
out_file = "~/Desktop/Graph6.pdf")

I get:

Error in process.image(append_class(resp, "image")) : Payment Required (HTTP 402).

Please advise
Jonathan

**Comment by cpsievert** [comment] 2017-03-08 20:21
Closing since the example is not reproducible. Happy to revisit if you have one.

**Closed by cpsievert** 2017-03-08 20:21 UTC

**Comment by flop71** [comment] 2017-03-14 10:40
@cpsievert  Not sure what you mean the "example is not reproducible" 

Are you saying if you export a graph as pdf it will export correctly?  I installed the latest devtools version and running:

 packageVersion('plotly')
‘4.5.6.9000’

I get the same 402 error as previously reported.

**Comment by cpsievert** [comment] 2017-03-14 15:12
I mean that you have provided no details on how to recreate  `field.defects.df.weekly.pc.bar`, and hence, reproduce the error.

**Comment by flop71** [comment] 2017-03-14 15:29
Dont worry about it. I figured it out. The issue is not tied to the plot rather it's tied to my subscription. (currently community)
