### ISSUE TITLE
geom_GeomArcBar() Implementation

### ISSUE THREAD

**Issue by MarcElosua** [ropensci/plotly#1736] opened 2020-04-05 12:44 UTC
Hi!
Thank you very much for developing and maintaining such a good package, it is super useful and very easy to use!
I ran into these warnings when I was trying to visualize scatterpie plots:

> 1: In geom2trace.default(dots[[1L]][[3L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>  geom_GeomArcBar() has yet to be implemented in plotly.
>  If you'd like to see this geom implemented,
> Please open an issue with your example code at
> https://github.com/ropensci/plotly/issues

Here is some minimal example code
```r
library(ggplot2)
library(scatterpie)
d <- data.frame(x=rnorm(5), y=rnorm(5))
d$A <- abs(rnorm(5, sd=1))
d$B <- abs(rnorm(5, sd=2))
d$C <- abs(rnorm(5, sd=3))
plt <- ggplot() + geom_scatterpie(aes(x=x, y=y), data=d, cols=c("A", "B", "C")) + coord_fixed()
plotly::ggplotly(plt)
```
Thank you very much!
Marc

**Comment by cpsievert** [comment] 2020-04-06 14:37
Thanks, if and when #1326 happens, this should automatically work. Closing since this is a duplicate of #566 (`GeomArcBar` is from ggforce)

**Closed by cpsievert** 2020-04-06 14:37 UTC
