### ISSUE TITLE
plotly geom doesnt implement

### ISSUE THREAD

**Issue by AbouDIA** [ropensci/plotly#1250] opened 2018-05-07 17:43 UTC
Warning in geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomTextRepel() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

---

Brief description of the problem

```r
ui:tabPanel("ACP",
           pageWithSidebar(
             
             headerPanel("We are using the package plotly"),
             
             sidebarPanel(
               
               selectInput("xGraphic","Visualisation avec:",choices = c("Valeurs propres","Graphe des variables","Graphe des individus","Biplot")),
               
               conditionalPanel(condition = "input.xGraphic=='Valeurs propres'"),
               conditionalPanel(condition = "input.xGraphic=='Graphe des variables'")
               #conditionalPanel(condition = "input.xGraphic=='Graphe des individus'" ),
               #conditionalPanel(condition = "input.xGraphic=='Biplot"),
             ),
             
             mainPanel(tabsetPanel(type="tabs",
              tabPanel("Outputs", plotlyOutput("acp")),
              tabPanel("ellipse",plotlyOutput("reg"))
           )))),
server:  {output$acp<-renderPlotly({gType<-input$xGraphic
  if(gType=="Valeurs propres"){fviz_eig(Xpca)}
  
  else if(gType=="Graphe des variables"){fviz_pca_var(ACP,col.var = "contrib",gradient.cols=c("#00AFBB", "#E7B800", "#FC4E07"),repel =TRUE)}
  
  else if(gType=="Graphe des individus"){fviz_pca_ind(ACP,col.ind = "cos2",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE)}
  
  else{fviz_pca_biplot(ACP, repel = TRUE,col.var = "#2E9FDF", col.ind = "#696969"  )}
  })}
  
  Xpca=dudi.pca(tablemeans.origine[,-c(24)],scale=TRUE,nf=3,scannf = FALSE)
  library(factoextra)
  fviz_eig(Xpca)
  fviz_pca_biplot(ACP, repel = TRUE,col.var = "#2E9FDF", col.ind = "#696969"  )
  fviz_pca_ind(ACP,col.ind = "cos2",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE)
  fviz_pca_var(ACP,col.var = "contrib",gradient.cols=c("#00AFBB", "#E7B800", "#FC4E07"),repel =TRUE)
 
   {output$reg<-renderPlotly({gType<-input$xGraphic
  {fviz_pca_ind(ACP,habillage = 24,addEllipses = TRUE)}
  })}
```

**Comment by cpsievert** [comment] 2018-05-07 18:52
Duplicate of #566

**Closed by cpsievert** 2018-05-07 18:52 UTC
