### ISSUE TITLE
  geom_GeomTextGGtree() to be implemented in plotly ?

### ISSUE THREAD

**Issue by Adri1CIRAD** [ropensci/plotly#1464] opened 2019-02-13 07:18 UTC
Hi there,

First thanks for working on this great and very useful package.

I'm plotting a ggtree with plotly and would like tip labels to be displayed.
However, I get the following error message suggesting this option is not implemented yet. Would it be possible to do it or is there another way to display tiplabels when plotting a ggtree with plotly ? This would be super useful...

Cheers,
Adrien

# LOAD LIBS
library(ape)
library(ggtree)
library(plotly)
# CREATE and PLOT TREE 
tree <- ape::rtree(n=20)
p <- ggtree(tree)
color_test=c(rep("black",20),rep("orange",10),rep("red",9))
alpha_test=c(rep(0.2,20),rep(1,19))
p1 <- p + geom_point(color=color_test, alpha=alpha_test, size=1.5) + geom_tiplab()
p1
plotly::ggplotly(p1)

Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomTextGGtree() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment] 2019-02-16 00:11
Duly noted, but duplicate of #566

**Closed by cpsievert** 2019-02-16 00:11 UTC
