### ISSUE TITLE
Subplot of scatterpolar plots

### ISSUE THREAD

**Issue by MohoWu** [ropensci/plotly#1677] opened 2019-12-31 15:37 UTC
When plotting multiple scatterpolars together in a `subplot`, is there a way to tell it not to plot all the points in the same plot, but having their own facet instead?

```r
library(plotly)
p1 <- plot_ly(
  type = 'scatterpolar',
  r = c(0,1,2,2),
  theta = c(0,45,90,0),
  mode = 'markers'
)

p2 <- plot_ly(
  type = 'scatterpolar',
  r = c(0,1,2,3),
  theta = c(0,45,90,0),
  mode = 'markers'
)

subplot(p1, p2)
```

**Comment by cpsievert** [comment] 2020-02-04 18:21
Duplicate of #1181

**Closed by cpsievert** 2020-02-04 18:21 UTC

**Comment by rafaelmenmell** [comment] 2020-02-05 13:13
I'm facing the same problem of @MohoWu , I want to plot together two scatterpolar plotly graphs, but when subplot them, they aren' shown side by side but fully overlapping.
The example @MohoWu provided was just perfect.
I have plolty version 4.9.1, and don't think it's solved

**Comment by stibemueller** [comment] 2022-04-07 21:07
I'm facing the same problem of @MohoWu and @rafaelmenmell  as well. Using plotly 4.10.0 and R 4.1.1.
Instead of plotting 2 scatterpolar plots side by side, it merges them into one plot.

**Comment by ratnanil** [comment] 2024-10-22 13:03
I'm facing the same problem of @MohoWu, @rafaelmenmell and @stibemueller  as well. I'm using plotly_4.10.4 and R 4.3.3. 

> Ah, the docs mention (https://plotly.com/r/subplots/#subplots-types) that subplots can only be made with cartesian coordinate systems.

So this is not going to be solved?
