### ISSUE TITLE
Feature Request: Skip Date with Missing Value

### ISSUE THREAD

**Issue by haodong** [ropensci/plotly#1172] opened 2017-12-30 12:30 UTC
Thank you for providing such a beautiful candlestick plot, which is often used for trading visulization. In reality, however, trading does not happen every day. We always get some missing date in our data due to weekends, holidays, or trading halts. We do not want them to show on the plots. Some of them may last for several months.

For example:

![image](https://user-images.githubusercontent.com/8103074/34106760-6734c362-e434-11e7-8c37-2b34d3676589.png)

![image](https://user-images.githubusercontent.com/8103074/34106847-cd3fbb8a-e434-11e7-90ab-4f0b901f58ec.png)

As a result, would you please add a new feature to omit those missing date with no data on candlestick plots?

[This issue](https://github.com/plotly/plotly.js/issues/1382) may be helpful, especially [these parameter conceptions](https://github.com/plotly/plotly.js/issues/1382#issuecomment-289487474).

**Comment by cpsievert** [comment] 2018-01-02 16:07
Duplicate of #1166. You could achieve what you want with `subplot()`s, but I will not be dedicating any time to this issue.

**Closed by cpsievert** 2018-01-02 16:07 UTC

**Comment by haodong** [comment] 2018-01-11 12:29
`subplot()` is a function to "View multiple plots in a single view".

You did not even see my content. 

What an arrogant man.

**Comment by cpsievert** [comment] 2018-05-26 15:31
@ogladkov I understand the problem and keep the position that you could hack together a solution with `subplot(..., shareY = TRUE)`. If you want a 'native' solution, follow this thread --  https://github.com/plotly/plotly.js/issues/1382

Not sure why this topic tends to attract such toxic behavior which is another big reason why I choose to ignore it.
