### ISSUE TITLE
missing waterfallgap attributes in plotly package  

### ISSUE THREAD

**Issue by Mahdis-z** [ropensci/plotly#1542] opened 2019-06-04 20:46 UTC
It seems that `waterfallgroupgap` and `waterfallgap` attributes were not added to Plotly package. <https://plot.ly/r/reference/#layout-waterfallgroupgap>. Running this code gives a  warning saying so. 

```r
library(plotly)

y = c(375, 128, 78, 0, -327, -78, 0, 32, 89, 0, -45, 0)
x = c("Sales", "Consulting", "Maintenance", "Net revenue", "Purchases", "Material expenses", "Operating profit", "Investment income", "Financial income",
"Profit before tax", "Income tax (15%)", "Profit after tax")
measure = c("relative", "relative", "relative", "total", "relative", "relative", "total", "relative", "relative", "total", "relative", "total")
data = data.frame(x=factor(x,levels = x), y, measure)

P <- plot_ly(data, x = ~x, y = ~y, measure = ~measure, type = "waterfall", base = 300, decreasing = list(marker = list(color = "Maroon", line = list(color = "red", width = 2))),
increasing = (marker = list(color = "Teal")),
totals = list(marker = list(color = "deep sky blue", line = list(color = 'blue', width = 3))))%>%
layout(title = "Profit and loss statement", xaxis = list(title = "", tickfont = "16", ticks = "outside"),
yaxis = list(title = ""), waterfallgap = "0.3")
P
```
```r
Warning message:
'layout' objects don't have these attributes: 'waterfallgap'
Valid attributes include:
'font', 'title', 'autosize', 'width', 'height', 'margin', 'paper_bgcolor', 'plot_bgcolor', 'separators', 'hidesources', 'showlegend', 'colorway', 'colorscale', 'datarevision', 'uirevision', 'editrevision', 'selectionrevision', 'template', 'modebar', 'meta', 'transition', '_deprecated', 'clickmode', 'dragmode', 'hovermode', 'hoverdistance', 'spikedistance', 'hoverlabel', 'selectdirection', 'grid', 'calendar', 'xaxis', 'yaxis', 'ternary', 'scene', 'geo', 'mapbox', 'polar', 'radialaxis', 'angularaxis', 'direction', 'orientation', 'editType', 'legend', 'annotations', 'shapes', 'images', 'updatemenus', 'sliders', 'metasrc', 'barmode', 'bargap', 'mapType'
```

**Comment by cpsievert** [comment] 2019-07-15 16:37
This warning is actually a false positive (e.g., if you compare the result of ` waterfallgap = 0` and` waterfallgap = 1`, the attribute is having the desired effect).

Closing since this is a duplicate of #994.

**Closed by cpsievert** 2019-07-15 16:37 UTC
