### ISSUE TITLE
Feature request: Use of (background) raster plots via ggplot2

### ISSUE THREAD

**Issue by boukepieter** [ropensci/plotly#682] opened 2016-08-15 12:57 UTC
I would like to include images or background maps to my plotly graphs/maps. For ggplot2 I use for example the functions ggmap() and annotation_custom() but these are nog yet implemented in ggplotly.

**Comment by cpsievert** [comment] 2016-08-15 14:03
Duplicate of #348

**Closed by cpsievert** 2016-08-15 14:03 UTC
