### ISSUE TITLE
geom_GeomDensityRidges() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by manolisathan** [ropensci/plotly#1645] opened 2019-10-22 10:03 UTC
The ggridges package provides two main geoms, geom_ridgeline and geom_density_ridges. The former takes height values directly to draw ridgelines, and the latter first estimates data densities and then draws those using ridgelines.

I would like to see this geom implemented

thanks in advance

**Comment by cpsievert** [comment] 2019-11-06 19:27
Duplicate of #566.

**Closed by cpsievert** 2019-11-06 19:27 UTC
