### ISSUE TITLE
some markers do not show the full KEY value on event_data() for plotly_click

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#505] opened 2016-03-13 18:55 UTC
I am testing the event_data() functionality to show the KEY value for a marker add_trace to ggplotly.

I noticed that while it works fine for most points that I select/over/lasso....it only shows the first CHARACTER for some of the points. It seems unusual why it is doing this.  

I am using the code based on the following example:  https://github.com/ropensci/plotly/blob/f1900cc3cd464408a60ffadfe3e95460747430e0/inst/examples/plotlyEvents/app.R

Any idea?

![image](https://cloud.githubusercontent.com/assets/14385814/13730665/74360a72-e92b-11e5-90aa-1f3813d5ab62.png)

**Comment by cpsievert** [comment] 2016-03-17 06:56
Hmm, I can't seem to replicate this, can you provide a reproducible example?

**Comment by ahsanshah** [comment] 2016-03-18 16:15
I am not able to replicate in a very simple example (such as the mtcars one we have). However, in my case this is an add_trace on top of a ggplotly geom within a Shiny Reactive.  Also, the EVENTS are generated withing dynamically as an API call via JSONlite.  

I can try to send you a minimal example but need to put one together. Would Shiny/Reactive behave any differently per my environment.

Also, How do we CONTROL what columns are returned by EVENT_DATA?  The default values (curve number, point number) are not needed for me. Is there any documentation on what EVENT_DATA returns and how we can control the output or add new columns?

**Comment by timelyportfolio** [comment] 2016-03-18 18:16
Without a reproducible example, I am having a hard time fully understanding what you are trying to get?  These [lines](https://github.com/ropensci/plotly/blob/master/inst/htmlwidgets/plotly.js#L37-L95) control the event data that is sent, so [lines](https://github.com/ropensci/plotly/blob/master/inst/htmlwidgets/plotly.js#L37-L95) send `curveNumber`, `pointNumber`, `x`, and `y`.  Then these [lines](https://github.com/ropensci/plotly/blob/master/inst/htmlwidgets/plotly.js#L61-L62) add `z` and `key` if available.  There does not currently appear to be an opportunity for customization.

I'm sure @cpsievert would be happy to explore adding this functionality or if not, I am happy to tackle.  An example would give me most of what I need to get started.

**Comment by ahsanshah** [comment] 2016-03-18 22:13
This one is weird.  I am not sure if it helps to send my entire app.r 600+ line code.  I cannot reproduce a minimal example.

However, What it seems like is that if i use a STATIC DATAFRAME, it does not have any issues with the MARKER values.  However, if I use a dynamic Shiny Reactive as an input, it does not capture the Markers for the event names. 

![image](https://cloud.githubusercontent.com/assets/14385814/13893472/075ccd92-ed35-11e5-9a60-69ebb9f436e6.png)

**Comment by timelyportfolio** [comment] 2016-03-19 00:17
Thanks, I should be able to look at this on Sunday also unless someone beats me to it.

**Comment by cpsievert** [comment] 2016-03-19 00:20
You can't currently control what variable(s) are returned by `event_data()`, although you can always subset according to your needs.

Also, your problems are probably due to the fact that `data` and `key` are the same object in your example?

**Comment by ahsanshah** [comment] 2016-03-19 19:03
It doesnt look like h"key" and "data" being the same is the issue.  As I said, if i use a static dataframe (with key and data being the same), it works fine. When I use a Reactive input (which I need to do) and set the data to be a full data frame and the key to be a specific column, it seems to result in a few "markers" not returning the proper values.  I am wondering how I can troubleshoot this.  As you can see below, it works for 9 markers and fails for 5.  In other words, using plotly_click or plotly_hover..the event_data() does not properly capture the marker values for a subset of the markers.  I cannot see any data anomalies with these specific markers at all.  

I am still going to try to see how I can minimize a reproduceable example but any thoughts are appreciated.  Also, as suggested, I have subset the event_data() output and merged it with a second data frame to control the output.  Thanks for that suggestion.  


![image](https://cloud.githubusercontent.com/assets/14385814/13900710/4705b52c-ede3-11e5-8cd8-9a5814f00b45.png)

**Comment by timelyportfolio** [comment] 2016-03-21 11:43
I tried a couple different ways to reproduce in Shiny with no luck.  When you say "I cannot see any data anomalies with these specific markers", is that on the R or the JavaScript side?  I would say that @cpsievert's suggestion to subset is better practice with or without Plotly.  Please let me know if you come up with something reproducible.

**Comment by cpsievert** [comment] 2016-03-25 00:34
Closing until someone can come up with a reproducible example.

**Comment by ahsanshah** [comment] 2016-03-26 16:56
I believe I have a reproducible case which illustrate this.  Attached is an app.R file and a RDS file to show the issue.  

Here is a screenshot of the behavior.  I have tested this across various data sets. For some reason, a subset of the markers do NOT show the correct KEY value for the EVENT_DATA.  It is the same behavor for CLICK, HOVER, or SELECT/DRAG. To show the example, I am using HOVER.

![image](https://cloud.githubusercontent.com/assets/14385814/14061256/f1b9acf8-f351-11e5-8f8c-c45bf2470f09.png)



Looking at the data frame, these 2 items have valid KEY values (e.g. event.id in my case)

![image](https://cloud.githubusercontent.com/assets/14385814/14061243/b2e0351a-f351-11e5-8f5f-948a6cc8ddfc.png)


Here are the files.  Let me know if you have questions. If this is indeed an issue, please reopen the case.

[Support.zip](https://github.com/ropensci/plotly/files/190546/Support.zip)

**Comment by cpsievert** [comment] 2016-03-26 22:57
You seem to have global vars floating around in that app, for instance, what is `test2`?

**Comment by ahsanshah** [comment] 2016-03-26 23:08
test2 is the dataset used for the geom_smooth in the ggplot prior to conversition to PLOTLY.  I have reuploaded the files with the test2.RDS.  I need both (geom_smooth) and ATLevents (Markers) on the plot.  However, I want the event_data to be based on the markers. 

Let me know if you can reproduce this on your end.  

[Support.zip](https://github.com/ropensci/plotly/files/190690/Support.zip)

**Comment by mauritzvdworm** [comment] 2016-08-29 15:40
I have noticed a similar issue using the event_data() function applied to a plotly image created from a reactive data frame.  No problem with a static data frame though.   In my case I have some data by county that I plot on a choropleth (map).  I want to add some additional information when you click on a specific country.  When the data frame is filtered and the plot redone the "plotly_click" does not select the correct points.

**Comment by SoloAus** [comment] 2016-12-16 14:03
Has anyone found a solution to this issue?

Hopefully this link can serve as a reproducible example: 
https://github.com/SoloAus/shiny-example/blob/master/app.R 

I need to use the id variable that is stored as 'key' to subset another dataframe and produce a subsequent plot under the map, but it is only returning the 1st character for id's with multiple characters.

**Comment by cpsievert** [comment] 2017-04-07 22:09
@SoloAus this appears to be working, right?

![screen shot 2017-04-07 at 5 08 53 pm](https://cloud.githubusercontent.com/assets/1365941/24821565/ef93dad4-1bb4-11e7-9570-7c70d888643b.png)

**Closed by cpsievert** 2017-04-07 22:09 UTC
