### ISSUE TITLE
Very bad performance of RMarkdown in Firefox

### ISSUE THREAD

**Issue by ischurov** [ropensci/plotly#483] opened 2016-03-07 14:29 UTC
I have RMarkdown document with several Plotly 3D charts. I convert it to HTML using RStudio's knitr and get HTML. This HTML file cannot be opened with Firefox: the browser starts complaining about unresponsive script, eats a lot of memory and finally hangs. The same charts created by Jupyter / IPython Notebook and converted to HTML can be opened with Firefox.

You can see the testcase [here](https://github.com/ischurov/hsequantling/tree/master/testcase).
1. [Original Rmd](https://github.com/ischurov/hsequantling/blob/master/testcase/lecture-pca-test.Rmd).
2. [HTML from Rmd](https://github.com/ischurov/hsequantling/blob/master/testcase/lecture-pca-test.html) that hangs my Firefox.
3. [Translation to Jupyter/IPython](https://github.com/ischurov/hsequantling/blob/master/testcase/Plotly%203D%20Testcase%20Jupyter-iPython.ipynb).
4. [HTML file from IPython](https://github.com/ischurov/hsequantling/blob/master/testcase/Plotly%203D%20Testcase%20Jupyter-iPython.html) that can be opened with Firefox.

I'm using Mac OS X and Firefox 44.0.2.

It seems to be more-or-less Firefox-specific issue as the test HTML file can be opened with Google Chrome and Safari.

**Comment by equastatjamesw** [comment] 2016-05-26 23:52
Opening this in Firefox 46.0.1 on Windows 10 I receive the warning message:
"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"
followed by an out of memory exception after allocation of more than 1GB.

The same issue happens for me when opening any HTML-Widgets based plotly charts saved to .html file from RStudio.  It appears that with a clean restart of Firefox I can often get one plot to load properly, although it is still very slow and consumes more than 1GB of RAM whereas opening the same .html in Chrome or Edge is fast and uses less than 100MB.

**Comment by ManuelZ** [comment] 2017-02-04 21:02
I'm having the same problem with Firefox 51.0.1 and Plotly 4.5.6 for R.

**Comment by mbannert** [comment] 2017-03-14 09:43
same here... any news on the issue? Problems seem to persist with FF 52.0 .

**Comment by cpsievert** [comment] 2017-04-06 21:09
note to self: hoping https://github.com/plotly/plotly.js/issues/1525 fixes this

**Comment by rreusser** [comment] 2017-04-07 16:27
If it's the same source, the `"mutating the [[Prototype]]…" warning` [comes from d3](https://github.com/plotly/plotly.js/issues/1445) and [won't be fixed](https://github.com/d3/d3/issues/1805#issuecomment-183684144). My best understanding is that it's a warning about best practices, but not one that has a measurable effect relative to a library like plotly.js.

I can definitely confirm that [the page](https://rawgit.com/ischurov/hsequantling/master/testcase/lecture-pca-test.html) is perfectly snappy in chrome and very problematic in firefox.

**Comment by cpsievert** [comment] 2017-04-07 19:29
Ok, this definitely has something to do with `self_contained: true` on Firefox as mentioned in #721. [Here](http://rpubs.com/cpsievert/266224) is a more minimal example that at least seems to render in Firefox, though it hogs up to 5GB of RAM on my system!


    ---
    title: "Open me in Firefox if you dare"
    output: 
    # set `self_contained: true` for fun times in Firefox
      html_document:
        self_contained: false
    ---
    
    ```{r, message = FALSE}
    library(plotly)
    plot_ly()
    ```

**Comment by DarioS** [comment] 2017-06-07 01:00
Thanks for the implicit tip. It worked for me once I used `self_contained: false` but I'd prefer if it worked when `self_contained: true`.

**Comment by Kabouik** [comment] 2017-10-12 09:19
I can confirm it works with `self_contained: false`, but would prefer it to work with `true` as well. Most of all, there should be a big warning about Firefox incompatibility, since it's a major browser and, not using it myself, I only realized there was an issue with my report when someone asked me "What figures?" when trying to read the report.

**Comment by cpsievert** [comment] 2018-04-17 15:59
I have a feeling this issue is related to the fact that pandoc <2.0 used data URIs to embed dependencies, but [pandoc >2.0 uses cleartext](https://github.com/ramnathv/htmlwidgets/pull/292).

Closing since upgrading to pandoc >2.0 seems to fix https://github.com/ropensci/plotly/issues/483#issuecomment-292630523, but please reopen if you find more (related) problems

**Closed by cpsievert** 2018-04-17 15:59 UTC
