### ISSUE TITLE
Autosize =F not working

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#504] opened 2016-03-13 15:54 UTC
It seems AUTOSIZE=F or "FALSE" does not work when I am using a ggplot conversion to plotly and adding a trace.  I tried setting AUTOSIZE in both the layout and the add_trace.  When I resize my browser window it is changing and rearranging my plots.

Note that I am plotting this on a Shiny Dashboard.  

Any idea how I can force it NOT to autosize when browser window is resized?

**Comment by cpsievert** [comment] 2016-03-13 23:25
Duplicate of #403

**Closed by cpsievert** 2016-03-13 23:25 UTC
