### ISSUE TITLE
Installation on OSX not working.

### ISSUE THREAD

**Issue by neuwirthe** [ropensci/plotly#291] opened 2015-10-28 16:25 UTC
I tried installing on OSX 10.11.1 with R 3.2.2 and got errors:

* installing *source* package ‘plotly’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in seq.default(1, idx - 1) : 'to' must be of length 1
Error : unable to load R code in package ‘plotly’
ERROR: lazy loading failed for package ‘plotly’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/plotly’
Error: Command failed (1)

**Comment by cpsievert** [comment] 2015-10-28 21:16
duplicate of #288

**Closed by cpsievert** 2015-10-28 21:16 UTC
