### ISSUE TITLE
event_data() triggering unexpected warning about registering

### ISSUE THREAD

**Issue by bklingen** [ropensci/plotly#1528] opened 2019-05-09 22:33 UTC
Using `event_data("plotly_hover", source="mysource")` seems to trigger the following warning with the newest plotly version:
`Warning: The 'plotly_hover' event tied a source ID of 'mysource' is not registered. In order to obtain this event data, please add event_register(p, 'plotly_hover') to the plot (p) that you wish to obtain event data from.`

```r
library(shiny)
library(plotly)

ui <- fluidPage(
        plotlyOutput("myplot"),
        verbatimTextOutput("hovered")
      )

server <- function(input, output, session) {
    
    output$myplot <- renderPlotly({
        p <- plot_ly(faithful, x=~eruptions, y=~waiting, source="mysource")
        return(p)
    })
    
    output$hovered <- renderPrint({
      event_data("plotly_hover", source="mysource")
    })

}

shinyApp(ui = ui, server = server)
```

**Comment by bklingen** [comment] 2019-05-10 01:20
The relevant entry from the plotly source code:
```{r}
# It's possible for event_data() to execute before any 
  # relevant input values have been registered (i.e, before 
  # relevant plotly graphs have been executed). Therefore, 
  # we delay checking that a relevant input value has been 
  # registered until shiny flushes
  session$onFlushed(
    function() {
      eventIDRegistered <- eventID %in% session$userData$plotlyShinyEventIDs
      if (!eventIDRegistered) {
        warning(
          "The '", event, "' event tied a source ID of '", source, "' ",
          "is not registered. In order to obtain this event data, ", 
          "please add `event_register(p, '", event, "')` to the plot (`p`) ",
          "that you wish to obtain event data from.",
          call. = FALSE
        )
      }
    }
  )```

**Comment by cpsievert** [comment] 2019-05-14 20:35
Huh, the warning seems to go away if you avoid `return()`

```r
library(shiny)
library(plotly)

ui <- fluidPage(
  plotlyOutput("myplot"),
  verbatimTextOutput("hovered")
)

server <- function(input, output, session) {
  
  output$myplot <- renderPlotly({
    plot_ly(faithful, x=~eruptions, y=~waiting, source="mysource")
  })
  
  output$hovered <- renderPrint({
    event_data("plotly_hover", source="mysource")
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by baj12** [comment] 2019-05-15 07:07
How would you handle returning NULL?
I need to stop plot when there is no data (or other criteria are not matched). Currently, I return(NULL),
but I guess this is not optimal. I would rather see a message saying that data needs be loaded, but I still haven't figured out how to do this...
And yes, I have the impression that without the return I see fewer warnings, but I still see some, most probably due to the return(NULL)...
Thanks a lot.
B

**Comment by dchen71** [comment] 2019-05-17 23:55
Are there any docs on how to use event_register? I recently upgrade to the newest plotly r version and am getting event_register errors on all of my scatter plots. I have two different sources for two different plots.

**Comment by madmark81** [comment] 2019-05-23 16:56
Same here, I see my other post is already referenced. Hope this will be fixed. Lost a full day to try to fix a work around but I still get slapped silly with the warnings.  

Hope this can be fixed / suppressed / removed

**Comment by cpsievert** [comment] 2019-05-24 19:48
> How would you handle returning NULL?

Avoid calling `event_data()` until the relevant output is non-NULL, like this https://github.com/ropensci/plotly/issues/1538#issuecomment-495312022

If someone can some with an example where this is sufficiently hard, I might be willing to add an official way to suppress the warning in `event_data()`

**Closed** 2019-08-30 17:04 UTC

**Comment by CDorich** [comment] 2021-09-15 17:51
I am still running into this issue of _Warning: The 'plotly_hover' event tied a source ID of 'mysource' is not registered. In order to obtain this event data, please add event_register(p, 'plotly_hover') to the plot (p) that you wish to obtain event data from._ 
I've copied Carson's code from this [post](https://stackoverflow.com/questions/47280032/draggable-line-chart-in-r-shiny), and mixed it with my own editable plotly in a test shiny app and can get it to work. When I run it in a larger app I am getting the same warning but the observe() or event_data("plotly_relayout") does not seem to be working with this app. I can get the shape to move but no underlying data is changing. I am completely stuck about how to get an event_register() to work and why I am not seeing any observe occur with the edited plot.... any guidance on how to code in an event_register() or why I can't see any interaction on this plot?

**Comment by sanjmeh** [comment] 2021-12-04 19:14
I started getting this warning as soon as I started using `source` argument in `plot_ly()`. Seems there is no clear cut solution to this as I see above. Is there any?

**Comment by davidseres** [comment] 2022-04-27 14:25
> You could give the warning a class so that these specific warnings could be turned off.
> 
> ```
>   session$onFlushed(
>     function() {
>       eventIDRegistered <- eventID %in% session$userData$plotlyShinyEventIDs
>       if (!eventIDRegistered) {
>         rlang::warn(
>           paste0("The '", event, "' event tied a source ID of '", source, "' ",
>           "is not registered. In order to obtain this event data, ", 
>           "please add `event_register(p, '", event, "')` to the plot (`p`) ",
>           "that you wish to obtain event data from."),
>           class = "plotly_unregistered_event_warning"
>         )
>       }
>     }
>   )
> ```
> 
> These warnings can be disabled in the shiny server code by wrapping this around the desired code
> 
> ```
> suppressWarnings(..., classes = "plotly_unregistered_event_warning")
> ```

Where does `eventID` come from?

**Comment by dvg-p4** [comment] 2024-01-31 18:52
> > How would you handle returning NULL?
> 
> Avoid calling `event_data()` until the relevant output is non-NULL, like this [#1538 (comment)](https://github.com/plotly/plotly.R/issues/1538#issuecomment-495312022)
> 
> If someone can some with an example where this is sufficiently hard, I might be willing to add an official way to suppress the warning in `event_data()`
> 
> > Are there any docs on how to use event_register?
> 
> Sort of, see `?event_register`. It's worth noting though that you shouldn't need to use `event_register()` unless you need an event that isn't registered by default...here's a hack to get at the default events:
> 

@cpsievert I'm a bit confused, if the recommended way to avoid this warning is a `req()` above the call, why is the warning message itself talking about `event_register()`?

**Comment by dvg-p4** [comment] 2024-01-31 20:57
Also, the `req()` method isn't working consistently for me in a larger app. IIUC when the `renderPlotly()` and the reactive holding `event_data()` are both depending on the same reactive, there's no guarantee as to which will be executed first when that reactive becomes available--so if the shiny reactive queue happens to execute the `event_data` first, we see the warning.

**Comment by asadow** [comment] 2024-10-16 19:29
@dvg-p4 

Hmm, maybe [this](https://github.com/plotly/plotly.R/issues/1538#issuecomment-2417756644) will help.

**Comment by trafficonese** [comment] 2024-12-03 10:59
### Addressing the Need to Suppress Warnings in `event_data()`

Regarding this statement, @cpsievert:

> If someone can some with an example where this is sufficiently hard, I might be willing to add an official way to suppress the warning in `event_data()`

Creating a minimal reproducible example from such applications is not only quite time-consuming but often fails to replicate the issue, as the warning tends to disappear in simpler scenarios while persisting in the more complex app. Additionally, the suggestion provided in the warning message itself does not address the root problem effectively.

> "In order to obtain this event data, please add `event_register(p, 'plotly_click')` to the plot (`p`) that you wish to obtain event data from."

Even when the recommended `event_register` calls are added to the `plot_ly()` function, the warnings persist:
```
output$plotlyplot <- renderPlotly({
  plot_ly(
    data = mtcars,
    x = ~mpg, y = ~carb,
    type = "scatter",
    mode = "markers"
  ) %>%
    event_register('plotly_hover') %>% 
    event_register('plotly_click') %>% 
    event_register('plotly_doubleclick')
})
```

### Cluttered Logs 

In larger Shiny applications with multiple pages for example and several interactive Plotly plots on each page, these warnings can quickly accumulate, so that the Log files become cluttered with unnecessary warnings, obscuring genuinely important warnings that need attention. This makes debugging significantly harder. Another complication is that we can't simply use `suppressWarnings()` to handle this issue effectively. In one of my apps, I had to resort to a workaround like this:

```
options(warn = -1)
# Perform some calculations and then create a Plotly plot
options(warn = 0)
```
This is far from ideal and can suppress more warnings than intended.

### Debugging Becomes Impossible with `options(warn = 2)`

Setting `options(warn = 2)` -which turns warnings into errors- causes the app to crash simply because interactive Plotly plots are used. This behavior blocks effective debugging.

### Example Shiny App

To illustrate, consider a Shiny app where users dynamically generate multiple plots based on selected time ranges. For simplicity, I’ve adapted the scenario to use a numeric input, allowing users to specify between 1 and 5 plots. Each plot supports interactivity via hover, click, and double-click events.
In such a case, the repetitive warnings for multiple plots add unnecessary noise to the logs (especially since everything seems to be working correctly!). While it might technically be possible to suppress these warnings correctly in this scenario, the process is neither obvious nor straightforward. This is evidenced by the number of related GitHub issues and StackOverflow questions, highlighting that many developers struggle with this same problem. The current behavior adds unnecessary complexity and frustration, making a proper solution or clear guidance essential.

```
library(shiny)
library(plotly)

# Simulated dataset generator
generate_data <- function(id) {
  data.frame(
    x = rnorm(50, mean = id * 5),
    y = rnorm(50, mean = id * 3),
    group = sample(letters[1:3], 50, replace = TRUE)
  )
}

# UI
ui <- fluidPage(
  titlePanel("Dynamic Plotly Plots"),
  sidebarLayout(
    sidebarPanel(
      numericInput("num_plots", "Number of Plots:", value = 1, min = 1, max = 5),
      verbatimTextOutput("hover_info"),
      verbatimTextOutput("click_info"),
      verbatimTextOutput("dblclick_info")
    ),
    mainPanel(
      uiOutput("plots_ui") # Placeholder for dynamically generated plots
    )
  )
)

# Server
server <- function(input, output, session) {
  plot_data <- reactive({
    lapply(1:input$num_plots, generate_data)
  })
  
  # Dynamically generate UI for plots
  output$plots_ui <- renderUI({
    num <- input$num_plots
    plot_output_list <- lapply(1:num, function(i) {
      plotlyOutput(outputId = paste0("plot_", i), height = "300px")
    })
    do.call(tagList, plot_output_list)
  })
  
  # Render dynamic plots
  observe({
    lapply(1:input$num_plots, function(i) {
      local({
        id <- i
        output[[paste0("plot_", id)]] <- renderPlotly({
          plot_ly(
            data = plot_data()[[id]],
            x = ~x, y = ~y,
            type = "scatter",
            mode = "markers",
            color = ~group,
            source = paste0("plot_source_", id),
            text = ~paste("Point ID:", 1:nrow(plot_data()[[id]]))
          ) %>%
            layout(title = paste("Dynamic Plot", id))
        })
      })
    })
  })
  
  # Observe Events (Click, Dbclick, Hover) for all plots
  observe({
    lapply(1:input$num_plots, function(i) {
      local({
        id <- i
        # observeEvent(event_data("plotly_hover", source = paste0("plot_source_", id)), {
        observe({
          req(plot_data())
          hover <- event_data("plotly_hover", source = paste0("plot_source_", id))
          if (!is.null(hover)) {
            output$hover_info <- renderText({
              paste("Hover on Plot", id, ":\nX =", hover$x, "\nY =", hover$y)
            })
          }
        })
        # observeEvent(event_data("plotly_click", source = paste0("plot_source_", id)), {
        observe({
          req(plot_data())
          click <- event_data("plotly_click", source = paste0("plot_source_", id))
          if (!is.null(click)) {
            output$click_info <- renderText({
              paste("Click on Plot", id, ":\nX =", click$x, "\nY =", click$y)
            })
          }
        })
        observe({
          req(plot_data())
          click <- event_data("plotly_doubleclick", source = paste0("plot_source_", id))
          if (!is.null(click)) {
            output$dblclick_info <- renderText({
              paste("DBL-Click on Plot", id, ":\nX =", click$x, "\nY =", click$y)
            })
          }
        })
      })
    })
  })
}

# Run the app
shinyApp(ui = ui, server = server)
```

**Comment by wmay** [comment] 2025-03-18 21:45
@cpsievert, I have an example where this is sufficiently hard-- seemingly impossible for all practical purposes.

I have an app where the plot height is set dynamically. This leads to a catch-22 situation where it is impossible to get the correct behavior without needless warnings that can't be suppressed.

Here's a simplified version:

```R
# dynamic plot height with click event
library(shiny)
library(plotly)

ui = fluidPage(
    titlePanel('event_data bug report'),
    radioButtons('height', 'Plot height',
                 c('Short' = '200', 'Tall' = '400'), '200'),
    h3('Last click update'),
    verbatimTextOutput('clickInfo'),
    uiOutput('dynamicTimeSeries')
)

server = function(input, output) {
  time_series_output = renderPlotly({
    y = if (input$height == '200') 1:5 else seq(1, 9, 2)
    plot_ly(x = 1:5, y = y, type = 'scatter', mode = 'lines',
            source = 'example', ) %>%
      event_register('plotly_click')
  })
  output$timeSeries = reactive(time_series_output())
  output$dynamicTimeSeries = renderUI({
    plotlyOutput('timeSeries', height = as.numeric(input$height))
  })
  output$clickInfo = renderPrint({
    req(time_series_output())
    print(Sys.time())
    event_data('plotly_click', 'example')
  })
}

shinyApp(ui = ui, server = server)
```

In general, using `event_data` with a dynamic plot has been a huge pain.

First, whatever you're trying to do with `session$onFlushed` when emitting the warning doesn't seem to work with a dynamic plot. I get false positive warnings.

To fix that, when responding to clicks, I need to call `req` to make sure the plot exists. I had to create a layer of indirection with a new variable, `time_series_output`, so that I have something to call `req` on.

Here's the catch-22: when I add this `req` statement before checking the click event, it adds a reactive dependency to the plot. That means every time the plot is updated, this code runs again. So now I can't update the plot without the click event running. When you run this example app, it shows that the click event is run every time the plot height is changed. Not only is it run again, but there's no way to distinguish real clicks from plot updates.

So I can either remove the false warnings, or I can have an app that responds correctly to click events, but I can't do both.

I propose a rule of thumb: if the warning is not suppressible, there should be an option to remove it. There's too much weird stuff happening within Shiny for you to guarantee users that it'll only warn at the correct times, and the hoops you want us to jump through are a lot more burdensome than simply turning off the warning.
