### ISSUE TITLE
Add geom_GeomSignif() to plotly

### ISSUE THREAD

**Issue by sayalitalware** [ropensci/plotly#1795] opened 2020-06-15 17:29 UTC
---

# Display the p-values on the plot.
# geom_GeomSignif() has yet to be implemented in plotly.

```r

plot_fun <- ggplot(metadata, aes(x = x, y = y, fill = Group, color = Group)) +
  ggplot2::geom_violin(trim = FALSE, alpha = 0.5, scale = "area", na.rm = TRUE, show.legend = FALSE) +
  ggplot2::geom_jitter(height = 0, width = 0.1) +
  ggplot2::geom_boxplot(width = 0.1, alpha = 0.75) +
  stat_compare_means(label = "p.format", method = "wilcox.test", comparisons = list(c("Case", "Control")))

plot <- plotly::ggplotly(plot_fun)

```

**Comment by cpsievert** [comment] 2020-06-22 19:17
Duplicate of #566

**Closed by cpsievert** 2020-06-22 19:17 UTC
