### ISSUE TITLE
auto axis date-range, setting to even hours?

### ISSUE THREAD

**Issue by smaettig** [ropensci/plotly#652] opened 2016-07-22 08:23 UTC
Hi everyone,
I am plotting a graph with a 25h date-range with minutely granularity, and would like to have 12 ticks every two hours. However, I would like to show only the even hours, i.e. 8:00, 10:00, 12:00 - but whatever I am entering into my axis configuration I **always** get uneven hours. 

Any ideas?

Thanks for your help!
Stefan

---------------------------------------------------------
Here is some R code to reproduce the problem:

visitsPerMinute <- data.frame(date=seq(as.POSIXct("2016-07-19 11:00:00 CEST"), as.POSIXct("2016-07-20 12:00:00 CEST"), by="min"))
visitsPerMinute$pageviews <- runif(1501, 1,50)

plotPageViews <- function(PageViews, binSize) {
  
  # Define fonts
  f <- list(family = "Arial", size = 15)
  
  # Configure x-axis
  a <- list(
    tickmode="auto",
    nticks=13,
    tickformat="%H:%M",
    ticklen = 5,
    tickwidth = 2,
    showgrid = FALSE, 
    showticklabels = TRUE,
    titlefont = f
  )
  
  # Configure y-axis
  y1 <- list(title = paste0("Page Views (",binSize, " Minute-Intervals)"),
             titlefont = f,
             showgrid = FALSE
  )
  
  # Plot pageviews
  plot_ly(PageViews, x = date, y = pageviews) %>%
    layout(xaxis = a, yaxis = y1, title = "")
}

**Comment by timelyportfolio** [comment] 2016-07-22 11:46
This is probably not the optimal solution, but I think it will get you closer.

```
visitsPerMinute <- data.frame(date=seq(as.POSIXct("2016-07-19 11:00:00 CEST"), as.POSIXct("2016-07-20 12:00:00 CEST"), by="min"), by="min"))
visitsPerMinute$pageviews <- runif(1501, 1,50)

plotPageViews <- function(PageViews, binSize) {
  
  # Define fonts
  f <- list(family = "Arial", size = 15)
  
  # Configure x-axis
  a <- list(
    tickvals = seq(as.POSIXct("2016-07-19 12:00:00 CEST"), as.POSIXct("2016-07-20 12:00:00 CEST"), by="2 hours"),
    tickformat = "%H:%M",
    ticklen = 5,
    tickwidth = 2,
    showgrid = FALSE, 
    showticklabels = TRUE,
    titlefont = f,
    title = "Time"
  )
  
  # Configure y-axis
  y1 <- list(title = paste0("Page Views (",binSize, " Minute-Intervals)"),
             titlefont = f,
             showgrid = FALSE
  )
  
  # Plot pageviews
  plot_ly(PageViews, x = ~date, y = ~pageviews) %>%
    layout(xaxis = a, yaxis = y1, title = "")
}
```

**Comment by smaettig** [comment] 2016-07-22 12:21
Thanks, that would indeed solve my problem! 

However, isn't that some kind of plotly bug? It really doesn't matter what the time range of the initial data.frame is, the displayed hours are always uneven.

**Comment by timelyportfolio** [comment] 2016-07-22 17:11
@smaettig, my understanding of `plotly` is limited, but based on what I know, `plotly` leverages `d3` for the generation of the axes.  I believe the always-odd stems from starting with `11:00` (an odd hour).  If you start at `12:00`, you should get always-even.  I am pretty sure that this is not a bug in `plotly` or `plotly.js`.

**Comment by timelyportfolio** [comment] 2016-07-22 22:06
Feel free to reopen, but I'll close this for now.  Thanks for using `plotly`.

**Closed by timelyportfolio** 2016-07-22 22:06 UTC

**Comment by smaettig** [comment] 2016-07-25 07:15
@timelyportfolio thanks for your reply. But no matter where you start with your time-range, you will **always** get uneven numbers on the axis (at least in all combinations I tried). You might be right about D3 however.
