### ISSUE TITLE
Axis failed to refresh after legend filter is enabled, leading to wrong interpretation

### ISSUE THREAD

**Issue by happyshows** [ropensci/plotly#680] opened 2016-08-11 22:46 UTC
uncheck flag = no
before:
![image](https://cloud.githubusercontent.com/assets/3208181/17607433/5201a254-5feb-11e6-81ca-2fb1998d850f.png)
after:
![image](https://cloud.githubusercontent.com/assets/3208181/17607439/5a1334b2-5feb-11e6-87ce-1e2a3ed7ce51.png)

source data
![image](https://cloud.githubusercontent.com/assets/3208181/17607464/826a9130-5feb-11e6-89a6-d31ef82b60c3.png)

```
p <- ggplot(data = src,aes(x=Week,y=USAGE,fill = usage_hi))+
        geom_bar(stat = 'identity',position = position_dodge())+
        theme_bw()+
        theme(
          panel.grid.major.x = element_blank(),
          panel.border = element_blank(),
          axis.text.x=element_text(angle=30, hjust=1)
        )+

        scale_y_continuous(labels = comma)+
        facet_grid(ResourceName+Facility~Quarter,
                   scales = 'free_x',space = "free",labeller = label_value,switch = 'both')

      ggplotly(p)
```

**Comment by cpsievert** [comment] 2017-04-21 22:54
Duplicate of #689

**Closed by cpsievert** 2017-04-21 22:54 UTC
Labels: ggplotly
