### ISSUE TITLE
No geom_label or geom_segment(arrow=__) support

### ISSUE THREAD

**Issue by MBarrows20** [ropensci/plotly#527] opened 2016-03-21 20:42 UTC
It seems that geom_label() is not yet supported while geom_text is. It would be nice to have the former for aesthetics purposes. 

I am also trying to draw arrows with geom_segment but the arrow heads seem to be ignored. example code is below:

```{r}
(ggplot(data=test1, aes(x=x, y=y))
        +geom_text(data=test1, label=row.names(test1), aes(x=x,y=y),
              nudge_x = .1,nudge_y=.1, color="black")
        + geom_segment(data=test1, lwd=.1, aes(x=0,y=0,xend=x, yend=y,
                                               colour='Arrow Label'),
                       arrow=arrow(length = unit(.5,"cm"))))
ggplotly()
```

**Comment by cpsievert** [comment] 2016-03-21 23:12
Duplicate of #348 and #469

**Closed by cpsievert** 2016-03-21 23:12 UTC
