### ISSUE TITLE
geom_dl labels do not appear in plotly

### ISSUE THREAD

**Issue by bac3917** [ropensci/plotly#1762] opened 2020-05-10 16:49 UTC
In creating ggplot graphics with R and the package [geom_dl](https://www.rdocumentation.org/packages/directlabels/versions/2020.1.31/topics/geom_dl), I receive the following message upon passing my graph to plotly:

In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values

Can plotly include geom_dl labels in the future?

**Comment by cpsievert** [comment] 2020-05-19 20:47
Maybe, but not likely anytime soon. Duplicate of #566

**Closed by cpsievert** 2020-05-19 20:47 UTC
