### ISSUE TITLE
Legend Scroll issues.

### ISSUE THREAD

**Issue by batra2** [ropensci/plotly#525] opened 2016-03-18 22:16 UTC
I have a Shiny dashboard where I am rendering events on y axis. The scroll for the legend works fine when I render the UI for the first time. 

But if I resize the UI or refresh the Page the scroll disappears.

![scroll issue](https://cloud.githubusercontent.com/assets/17817507/13893529/6b9a41fe-ed35-11e5-93ae-056f41d24d65.png)

**Comment by timelyportfolio** [comment] 2016-03-18 23:23
Ok thanks for additional info.  I think this makes more sense.  I should be able to try to replicate Sunday.

**Comment by ahsanshah** [comment] 2016-03-18 23:31
Thanks.  I'm trying to do the same.  I don't think the issue is related to the API or my specific data set.  Also it is very random..there is no similarities between which key values do or do not have the full value verus just the firs character.  If I can get a reproduce able example I'll send across.  Also, given we can't customize the output of event_data...how can I persist specific columns to an external database.  I tried using $V5 to select a column from the plotly_selected event_data but that does not work.  How would we allow the click events to save and persist specific columns?  I assume I am missing somethin here.

**Comment by cpsievert** [comment] 2016-03-19 06:24
This seems like a plotly.js problem. @timelyportfolio I know the plotly.js folks like reproducible example using codepen, if possible.

**Comment by timelyportfolio** [comment] 2016-03-21 19:46
Looking at this, I have not yet replicated it on just the JavaScript side (see [codepen](http://codepen.io/timelyportfolio/pen/dMvgqd)).  I'll try to add some lines to see if that reproduces the issue.  @batra2, if you can recreate with a minimal reproducible example, I would really appreciate it.

**Comment by timelyportfolio** [comment] 2016-03-21 20:18
@batra2, I have been able to reproduce in R, so an example is no longer necessary.  I'll let you know what I can find out.

**Comment by timelyportfolio** [comment] 2016-03-21 20:38
@cpsievert, I replicated with the following code and noticed another sort-of-related problem.  The legend scroll `rect` appears but has no impact in RStudio/Windows, but works as expected in Chrome and Firefox.  Does the legend `rect` respond to drag in your RStudio?

````
#issue 525
#  Legend Scroll issues
#  issue states happens on resize with shiny
#  but I can replicate without shiny
#  as shown below

library(ggplot2)
library(plotly)
library(dplyr)

ggplotly(
  ggplot(
    mtcars%>%add_rownames(),
    aes(mpg,hp,color=rowname)
  ) +
    geom_point() +
    geom_smooth(
      aes(mpg,hp),
      inherit.aes=FALSE
    )
)
```

**Comment by cpsievert** [comment] 2016-03-21 23:19
Everything works as expected for me in Chrome/Firefox, but I can't seem to click and drag the scroll bar in RStudio (mouse scroll is working, though).

**Comment by timelyportfolio** [comment] 2016-03-22 13:31
Ok, same with me.  Do you think I should file an issue on plotly.js or just accept that this is a limitation of RStudio Viewer (perhaps `webkit`) similar to #322?

I'll switch focus now back to the issue with legend scrolling on resize.

**Comment by timelyportfolio** [comment] 2016-03-22 14:15
I think this gets fixed in `v.1.7.0` (see https://github.com/plotly/plotly.js/commit/7b393d43987dab29556ac204ffd2a670bea02f06#diff-f48c57dae9095e916f13f364ae740f69).

**Comment by timelyportfolio** [comment] 2016-03-22 14:21
Unfortunately, problem still there even though the scrolling legend behaves much better.  I'll research a little more and file issue over on plotly.js.

**Comment by timelyportfolio** [comment] 2016-04-07 01:37
This should now be fixed.  Please reopen if you are still having trouble after updating to the newest version.

**Closed by timelyportfolio** 2016-04-07 01:37 UTC
Labels: plotly.js
