### ISSUE TITLE
ggplotly not working after using coord_polar function

### ISSUE THREAD

**Issue by iatal** [ropensci/plotly#760] opened 2016-10-12 08:08 UTC
Hi,
I am trying to `ggplotly` a ggplot object after using the `coord_polar()` function, but it is not working. Even in the [example](http://ropensci.github.io/plotly/ggplot2/coord_polar.html) you give to users it does not work:

`pie <- ggplot(mtcars, aes(x = factor(1), fill = factor(cyl))) +
 geom_bar(width = 1)`
`ggplotly(pie + coord_polar(theta = "y"))`

**Error in zero_range(to) : x must be length 1 or 2
In addition: Warning messages:
1: In min(z$x.range) : no non-missing arguments to min; returning Inf
2: In max(z$x.range) : no non-missing arguments to max; returning -Inf
3: In min(z$y.range) : no non-missing arguments to min; returning Inf
4: In max(z$y.range) : no non-missing arguments to max; returning -Inf**

Thanks

**Comment by cpsievert** [comment] 2016-10-12 15:13
duplicate of #491

**Closed by cpsievert** 2016-10-12 15:13 UTC
