### ISSUE TITLE
calling facet_wrap do not work anymore in ggplotly

### ISSUE THREAD

**Issue by statquant** [ropensci/plotly#1818] opened 2020-07-17 07:47 UTC
Hello, it seems that using `facet_wrap` does not work anymore

```
R --vanilla
```                                             

Then using example from website

```
library(reshape2)
library(plotly)
p <- ggplot(tips, aes(x=total_bill, y=tip/total_bill)) + geom_point(shape=1)
# Divide by day, going horizontally and wrapping with 2 columns
p <- p + facet_wrap( ~ day, ncol=2)
fig <- ggplotly(p)
Error in mutate_impl(.data, dots, caller_env()) :
  attempt to bind a variable to R_UnboundValue   
```

```
> sessionInfo()                                                             
R version 4.0.0 (2020-04-24)                                                
Platform: x86_64-pc-linux-gnu (64-bit)                                      
Running under: CentOS Linux 7 (Core)                                        
                                                                            
Matrix products: default                                                    
BLAS:   /usr/lib64/libblas.so.3.4.2                                         
LAPACK: /usr/lib64/liblapack.so.3.4.2                                       
                                                                            
locale:                                                                     
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C                                 
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8                        
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8                       
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                                    
 [9] LC_ADDRESS=C              LC_TELEPHONE=C                               
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C                          
                                                                            
attached base packages:                                                     
[1] stats     graphics  grDevices utils     datasets  methods   base        
                                                                            
other attached packages:                                                    
[1] plotly_4.9.2.1 ggplot2_3.3.2  reshape2_1.4.3                            
                                                                            
loaded via a namespace (and not attached):                                  
 [1] Rcpp_1.0.4.6      magrittr_1.5      tidyselect_1.0.0  munsell_0.5.0    
 [5] viridisLite_0.3.0 colorspace_1.4-1  R6_2.4.1          rlang_0.4.6      
 [9] httr_1.4.1        stringr_1.4.0     plyr_1.8.5        dplyr_0.8.4      
[13] tools_4.0.0       grid_4.0.0        data.table_1.12.9 gtable_0.3.0     
[17] withr_2.2.0       htmltools_0.4.0   ellipsis_0.3.1    lazyeval_0.2.2   
[21] digest_0.6.25     assertthat_0.2.1  tibble_3.0.1      lifecycle_0.2.0  
[25] crayon_1.3.4      tidyr_1.0.2       purrr_0.3.4       htmlwidgets_1.5.1
[29] vctrs_0.3.0       glue_1.4.1        labeling_0.3      stringi_1.4.6    
[33] compiler_4.0.0    pillar_1.4.4      scales_1.1.0      jsonlite_1.6.1   
[37] pkgconfig_2.0.3    
```

**Comment by statquant** [comment] 2020-07-17 07:58
Actually I checked dplyr and updating to 1.0.0 now triggers a warning instead

```
library(reshape2)
library(plotly)
p <- ggplot(tips, aes(x=total_bill, y=tip/total_bill)) + geom_point(shape=1)
# Divide by day, going horizontally and wrapping with 2 columns
p <- p + facet_wrap( ~ day, ncol=2)
fig <- ggplotly(p)
Warning message:                                                           
`group_by_()` is deprecated as of dplyr 0.7.0.                             
Please use `group_by()` instead.                                           
See vignette('programming') for more help                                  
This warning is displayed once every 8 hours.                              
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

sessionInfo is 

```
R version 4.0.0 (2020-04-24)                                                
Platform: x86_64-pc-linux-gnu (64-bit)                                      
Running under: CentOS Linux 7 (Core)                                        
                                                                            
Matrix products: default                                                    
BLAS:   /usr/lib64/libblas.so.3.4.2                                         
LAPACK: /usr/lib64/liblapack.so.3.4.2                                       
                                                                            
locale:                                                                     
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C                                 
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8                        
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8                       
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                                    
 [9] LC_ADDRESS=C              LC_TELEPHONE=C                               
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C                          
                                                                            
attached base packages:                                                     
[1] stats     graphics  grDevices utils     datasets  methods   base        
                                                                            
other attached packages:                                                    
[1] plotly_4.9.2.1 ggplot2_3.3.2  reshape2_1.4.3                            
                                                                            
loaded via a namespace (and not attached):                                  
 [1] Rcpp_1.0.4.6      magrittr_1.5      tidyselect_1.1.0  munsell_0.5.0    
 [5] viridisLite_0.3.0 colorspace_1.4-1  R6_2.4.1          rlang_0.4.6      
 [9] httr_1.4.1        stringr_1.4.0     plyr_1.8.5        dplyr_1.0.0      
[13] tools_4.0.0       grid_4.0.0        data.table_1.12.9 gtable_0.3.0     
[17] withr_2.2.0       crosstalk_1.1.0.1 htmltools_0.4.0   ellipsis_0.3.1   
[21] lazyeval_0.2.2    digest_0.6.25     tibble_3.0.1      lifecycle_0.2.0  
[25] crayon_1.3.4      tidyr_1.0.2       purrr_0.3.4       htmlwidgets_1.5.1
[29] vctrs_0.3.0       glue_1.4.1        labeling_0.3      stringi_1.4.6    
[33] compiler_4.0.0    pillar_1.4.4      generics_0.0.2    scales_1.1.0     
[37] jsonlite_1.6.1    pkgconfig_2.0.3    
```

**Comment by cpsievert** [comment] 2020-07-22 14:45
Duplicate of #1783

**Closed by cpsievert** 2020-07-22 14:45 UTC
