### ISSUE TITLE
geom_text_repel

### ISSUE THREAD

**Issue by KasperSkytte** [ropensci/plotly#904] opened 2017-03-15 17:20 UTC
Would be super awesome if geom_text_repel() would work with plotly since I mainly use plotly for plots totally crowded with text

**Comment by cpsievert** [comment] 2017-03-15 18:06
Duplicate of #566

**Closed by cpsievert** 2017-03-15 18:06 UTC

**Comment by klin333** [comment] 2020-03-26 07:34
if anyone is desperate for ggrepel in plotly, you can always use the non-exposed internal functions of ggrepel to compute the repelled label x y coordinates, then plot the already repelled coordinates with plotly via the standard geom_text. Of course this isn't supported by ggrepel and will be very brittle, you will have to mess around with function arguments depending on ggrepel version. 

```
library(tidyverse)
library(stringr)

# my packages: plotly_4.9.2;  ggplot2_3.2.1; ggrepel_0.8.0 
repel_coords <- function(x, y, label, char_width, char_height, xlim, ylim, trans_x = 'identity', trans_y = 'identity', var_names = c('repel_x', 'repel_y'), 
                         point_padding_x = 0, point_padding_y = 0, hjust = 0, vjust = 0, maxiter = 8000, force = 1e-6, direction = 'both') {
  N <- length(x)
  hjust <- rep(hjust, N)
  vjust <- rep(vjust, N)
  
  exp10 <- function(x) 10^x
  trans_map <- c(
    'log' = 'exp',
    'log10' = 'exp10',
    'identity' = 'identity'
  )
  stopifnot(trans_x %in% names(trans_map))
  stopifnot(trans_y %in% names(trans_map))
  inv_x <- get(trans_map[trans_x])
  inv_y <- get(trans_map[trans_y])
  trans_x <- get(trans_x)
  trans_y <- get(trans_y)
  
  x <- trans_x(x)
  xlim <- trans_x(xlim)
  y <- trans_y(y)
  ylim <- trans_y(ylim)
  
  data_points <- tibble(x, y) %>% as.matrix()
  l <- str_split(label, '\n')
  heights <- map_dbl(l, length) * char_height
  widths <- map_dbl(l, compose(max, str_length)) * char_width
  boxes <- tibble(x-widths/2, y-heights/2, x+widths/2, y+heights/2) %>% as.matrix()
  df <- ggrepel:::repel_boxes(data_points, point_padding_x, point_padding_y, boxes, xlim, ylim, hjust, vjust, maxiter = maxiter, force = force, direction = direction)
  df <- as_tibble(df)
  
  df$x <- inv_x(df$x)
  df$y <- inv_y(df$y)
  
  df <- df %>% set_names(var_names)
  df
}

# example usage
data_df <- tibble(x = rnorm(30, 0, 5), y = rnorm(30, 0, 5))

label_df <- tribble(
  ~x, ~y, ~label,
  1,  2,  'item1',
  1,  2.1, 'item2',
  3,  4, 'item3',
  3.1,  4, 'item4'
) %>%
  nest() %>%
  mutate(repel = map(data, function(d) repel_coords(d$x, d$y, d$label, 1, 1, c(-10, 10), c(-10, 10), force = 1e-4))) %>%
  unnest()

pl <- data_df %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point() + 
  geom_point(data = label_df, color = 'red') + 
  # geom_text(data = label_df, aes(label = label)) 
  geom_text(data = label_df, aes(x = repel_x, y = repel_y, label = label))

```

**Comment by cpsievert** [comment] 2020-03-26 14:35
Nice @klin333! If you were to post this example code on https://community.rstudio.com/ I'm sure it would get a lot more visibility :)
