### ISSUE TITLE
in shiny can't use annotation custom

### ISSUE THREAD

**Issue by o10o** [ropensci/plotly#1217] opened 2018-03-14 17:25 UTC
I need to put a background image in my graph.

I tried with ggplot it was working.
My code in ggplot is
court<-readPNG("./img/Lakers2.PNG")
gcourt<- rasterGrob(court, width=unit(1,"npc"), height=unit(1,"npc"),interpolate=TRUE)
ggplot(sh_mis) + 
    annotation_custom(gcourt, -Inf, Inf, -Inf, Inf) +
  geom_hex(aes(x=loc_x, y=loc_y,fill = cut(sqrt(loc_x^2+loc_y^2),decoup )), data=sh_mis, stat=StatIdentity, bins=500)+
  scale_fill_brewer(palette = "GnBu",
                    labels = c("<100", "100-250", "250-500",
                               "500-1000", "1000-1500",
                               "1500-2000", "2000-2500",
                               ">2500"))+
  theme(legend.position="none") +
  xlim(-150, 150) +
    ylim(-5, 790)

My code for shiny  is 
output$plot <- renderPlotly({
        decoup<-c(0, 100, 250, 500, 1000, 1500, 2000, 2500, Inf)
        court<-readPNG("./www/Lakers2.PNG")
        gcourt<- rasterGrob(court, width=unit(1,"npc"), height=unit(1,"npc"),interpolate=TRUE)
        p<-ggplot(sh) + 
            annotation_custom(gcourt, -Inf, Inf, -Inf, Inf) +
            geom_hex(aes(x=loc_x, y=loc_y,fill = cut(sqrt(loc_x^2+loc_y^2),decoup )), data=sh, stat=StatIdentity, bins=500)+
            scale_fill_brewer(palette = "GnBu",
                              labels = c("<100", "100-250", "250-500",
                                         "500-1000", "1000-1500",
                                         "1500-2000", "2000-2500",
                                         ">2500"))+
            theme(legend.position="none") 
         ggplotly(p,tooltip="text")
    })

when I tried to implent it in ggplotly an error message appears
  geom_GeomCustomAnn() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

It seems like that annotation_custom doesn't work, is it possible to implement it?

**Comment by cpsievert** [comment] 2018-03-14 17:39
Duplicate of #348

**Comment by cpsievert** [comment] 2018-03-14 17:40
This sort of thing can be done via `layout.images`, see `?raster2uri`

**Closed by cpsievert** 2018-03-14 17:39 UTC
