### ISSUE TITLE
Offline maps for geo plot

### ISSUE THREAD

**Issue by fabiangehring** [ropensci/plotly#835] opened 2016-12-21 10:31 UTC
When creating geo-plots as desribed here:
http://stackoverflow.com/questions/41244423/plotly-geoplot-working-in-ie-but-not-chrome-or-firefox

and using in a browser without internet connection, the map is not shown. Is it possible to include the maps for offline usage?

**Comment by cpsievert** [comment] 2016-12-21 16:26
Duplicate of #356

**Closed by cpsievert** 2016-12-21 16:26 UTC
