### ISSUE TITLE
Enhance geom_text() to adjust text angle

### ISSUE THREAD

**Issue by cdr6934** [ropensci/plotly#953] opened 2017-04-20 03:38 UTC
Following using plotly 4.5.6, I am not sure if it is a feature that has yet to be created; but the text label does not turn on its axis as can be seen in the static version of the plot. Following is some reproducible code that will demonstrate both graphs of interest. 

``` r
library(tidyverse) 
library(plotly) 

#Generate Sample Dataset 
gp <- c(0.2,0.1,0.2,0.4)
qrt <- c("Q1","Q1","Q2","Q2")
Deal <- c("ABC","DEF","ABC","DEF")

oneDealSample <- data.frame(ClosedYearQuarter = qrt, GP = gp, Family = Deal)

# GGPLOT
gpPlot <- ggplot(oneDealSample, aes(ClosedYearQuarter, GP, group=Family)) + 
  geom_col(aes(fill = Family), position = "dodge", show.legend = FALSE) + 
  geom_text(aes(label=round(GP*100,1), y = GP+.01), size = 2,angle=90, position = position_dodge(0.9), vjust =0) + 
  labs(x="Quarter", title=paste0("Turns by Deal Family by Quarter "), subtitle="Q1 2016 - Q1 2017") +
  scale_fill_brewer(palette = "GnBu") +
  guides(fill=FALSE)

# Static GGPLOT2 Graph
gpPlot

#Dynamic ggPlot2 Graph
ggplotly(gpPlot)

```
## Static ggPlot Graph
<img width="496" alt="screenshot" src="https://cloud.githubusercontent.com/assets/838118/25212261/ef1daa64-254e-11e7-929e-2ababe7cc570.png">

## Plotly Dynamic  ggPlot Graph
<img width="470" alt="screenshot" src="https://cloud.githubusercontent.com/assets/838118/25212263/f17c2b14-254e-11e7-9486-e6cda049aefd.png">

**Comment by cpsievert** [comment] 2017-04-20 04:53
duplicate of #709

**Closed by cpsievert** 2017-04-20 04:53 UTC

**Comment by phillip-richmond-umoja** [comment] 2024-06-27 15:39
Still an issue in 2024!
