### ISSUE TITLE
Linux Date GGPLOT converter

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#534] opened 2016-03-26 23:40 UTC
This is a follow up to a previous closed issue with regard to hover over (https://github.com/ropensci/plotly/issues/482).  

I am using the following logic to handle the Linux millisecond from Epoch (which btw I cannot understand why this is not classified as a bug).  

as.numeric(startlocal) * 24 * 60 * 60 * 1000,

I can render my charts fine but I would like to NOT see the millisecond at all on the plotly hover.  RIght now, I can only see a proper "DATE" if I have a data set that corresponds to that date. However, everything else shows the milisecond value. 

Can we not default to a valid DATE natively on Linux or coerce Plotly/ggplot to show an actual DATE.  Ideally the X axis should be at the DATE grain so that we see a valid date.  

![image](https://cloud.githubusercontent.com/assets/14385814/14062968/77d17fe0-f38a-11e5-8aca-9f32aa5a3825.png)

Let me know if you need a reproducible case. It should be easy to reproduce on linux for any DATE data set on the X axis..

**Comment by cpsievert** [comment] 2016-03-26 23:52
Duplicate of #502

**Closed by cpsievert** 2016-03-26 23:52 UTC
