### ISSUE TITLE
geom_GeomArcBar() with plotly

### ISSUE THREAD

**Issue by jheslavas** [ropensci/plotly#1431] opened 2018-12-09 16:28 UTC
I am trying to use plotly with a GeomArcBar function of ggplot2 in Shiny (RStudio). This is the warning message that I got: 

geom_GeomArcBar() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

The shiny app is running without plotly function in: 

http://medicina.bogota.unal.edu.co/equidad-en-salud

(it is an inequity-in-health index that we did for the Observatory of Equity-in-Health of the National Institute of Health in Colombia) (Just click on selected and refresh)

This is part of the code that we are using in the server section of shiny
```{r, }
 output$viewUltimate4 <- renderPlotly({
                        
                gg1 <- ggplot()+xlim(-1,1)+ylim(-1,1)+geom_arc_bar(aes(x0=0,y0=0,r0=0, r=datainput(),start= arcs$deg1_women*pi/180, end= arcs$deg2_women*pi/180, fill = Variable, col = Variable),data=arcs,n=360,na.rm=FALSE,show.legend = TRUE) + labs(x = "Vector = AF,  Angle=Weight", y ="")+ labs(title="Inequity in Health Composite Index - Colombia - Women")
                     
                fkl <- isolate(arcs1$qwe)
                fjk <- isolate(arcs1[,tgh()])
                
                
                #  nm <- isolate(arcs[,qwe])
                
                fnm <- isolate(arcs1[,tgh()])
                
                frm <- as.numeric(fnm)
                
                fty <- as.vector(frm)
                #class(ty) 
                
                print(fkl)
                print(fjk)
                print(fnm)
                print(frm)
                print(fty)
                
                fdatainput <- reactive({
                        
                        fty
                        
                })   
                        arcs1$Variable <- factor(arcs1$Variable, levels = arcs1$Variable[order(c("Accidente_transito ", "Agresiones ", "Enfermedad renal ", "Enfermedad respiratoria ", "Hemorrágicos_isquémicos ", "HIV ", "Mortalidad_menos5 años ",  "Meningitis ", "Parasitosis_intestinal ", "Sífilis ", "Transmisión_fecal_oral ", "Tuberculosis ", "Vectores "))])

               gg2 <- ggplot()+xlim(-1,1)+ylim(-1,1)+geom_arc_bar(aes(x0=0,y0=0,r0=0,  r=fdatainput(),start=arcs1$deg1_men*pi/180, end = arcs1$deg2_men*pi/180, fill = Variable, col = Variable),  data = arcs1, n = 360, na.rm = FALSE, show.legend = TRUE) +    labs(x = "Vector=AF,Angle=Weight",y="")+labs(title="Inequity in Health Composite Index - Colombia - Men")
        subplot(gg1, gg2) %>% layout(margin = list(l = 50))          
                })
        })
}

**Comment by cpsievert** [comment] 2018-12-10 15:43
Duplicate of #566 (ggforce)

**Closed by cpsievert** 2018-12-10 15:43 UTC
