### ISSUE TITLE
request to implement geom_GeomPointGGtree() in plotly

### ISSUE THREAD

**Issue by schultzm** [ropensci/plotly#758] opened 2016-10-11 00:37 UTC
Hi, 

When trying to run:
```
t <- ggtree(tre) %<+% blocks +geom_tippoint(aes(colour=gene))
ggplotly(t)
```

I get the message 
```
Warning messages:
1: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomPointGGtree() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```

Thanks, 

Mark

**Comment by cpsievert** [comment] 2016-10-12 15:02
duplicate of #757

**Closed by cpsievert** 2016-10-12 15:02 UTC
