### ISSUE TITLE
Create geom_edge for work with `ggraph` in R

### ISSUE THREAD

**Issue by ElliotMeador84** [ropensci/plotly#1891] opened 2020-11-26 15:35 UTC
---

Brief description of the problem

```r
library(tidyverse)
library(ggraph)
library(plotly)

g <- igraph::erdos.renyi.game(25, .1)


g_graph <- ggraph(g)+
  geom_edge_fan()+
  geom_node_point()

plotly::ggplotly(g_graph)

```
Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomEdgePath() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment] 2020-12-08 23:28
Duplicate of #566

**Closed by cpsievert** 2020-12-08 23:28 UTC
