### ISSUE TITLE
Infinite filename and UI crash on Cinnamon and MATE while saving 

### ISSUE THREAD

**Issue by franc00018** [ropensci/plotly#763] opened 2016-10-16 05:16 UTC
When I try to save a Plotly graph generated with RStudio, using the Download Plot as PNG, it opens a saving windows with file name being generated as AAA...AAA with a seemingly nonstop stream of "A" in the file name. The desktop environment "Cinnamon" or "MATE" then crashes or produce an error message.

Example code (anything will do)

```
library(plotly)
my_data = data.frame(Name=paste0("Value",1:100), Valeur = runif(100))
plot_ly(data = my_data, 
        y = ~Valeur, 
        x = ~Name, 
        type = 'bar', 
        orientation = 'v', 
        marker = list(color = 'rgba(38, 24, 74, 0.8)',
                      line = list(color = 'rgb(248, 248, 249)',
                                  width = 1.5)))
```

[I recorded a videocast of the behavior](https://framadrop.org/r/woxonn86L2#z2Sgwwv84Isvz+wLWAwlz7CHqLMiXBJOnD/ew1Zjq4Y=)

**Comment by cpsievert** [comment] 2016-12-01 00:37
Duplicate of #672

**Closed by cpsievert** 2016-12-01 00:37 UTC
