### ISSUE TITLE
Plotly heatmap in a flexdashboard document

### ISSUE THREAD

**Issue by Haunfelder** [ropensci/plotly#1524] opened 2019-05-07 17:17 UTC
I’m having a very specific problem with a plotly heatmap object inserted in a two tabbed flexdashboard rmarkdown. The MRE below, when rendered, displays an uncaught axis resizing javascript error. The error causes the heatmap to not render on the second tab. However, if the heatmap is moved to the same tab both will render without a problem. The craziest part is that a hard refresh of the html document (ctrl+f5 in browser) with the second tab open causes the javascript error to disappear and everything renders just fine.  I am using the most current version of all packages on CRAN and the newest R release 3.6.0.  I am having a very difficult time isolating this issue to the plotly R API, but I believe the most recent update is the source of the issue since I cannot reproduce in an older verison of R (3.5.2) and version of plotly (4.8.0.9000). Any ideas?

[SO Post](https://stackoverflow.com/questions/55975837/heatmap-in-rmarkdown-flexdashboard?noredirect=1#comment98695238_55975837)

````r
---
title: "`r paste0('Test')`"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
    self_contained: false
---

```{r setup, include=FALSE}
library(flexdashboard)
library(reshape2)
library(dplyr)
library(ggplot2)
library(plotly)
```

Tab1
===================================================

Row
-----------------------------------------------------------------------

### A scatter

```{r fig1}
df = data.frame(x = 1:5, y = 1:5, z = 1:5)
plot_ly(df, x = ~x, y = ~y, type = "scatter")
```

Tab2 
===================================================

Row
-----------------------------------------------------------------------

### A heatmap

```{r fig2}
plot_ly(df, x = ~x, y = ~y, z = ~z, type = "heatmap")
```
````

**Comment by cpsievert** [comment] 2019-07-11 21:54
Probably a duplicate of #1546

**Comment by cpsievert** [comment] 2019-08-30 19:24
Looks like you can workaround this problem by doing:

```r
plot_ly(df, x = ~x, y = ~y, z = ~z, type = "heatmap") %>%
  config(fillFrame = TRUE)
```

**Comment by cpsievert** [comment] 2019-08-30 19:24
Closing since this is a duplicate of #1546 (and there is more/better information there)

**Closed by cpsievert** 2019-08-30 19:24 UTC
Labels: plotly.js
