### ISSUE TITLE
xlab position 

### ISSUE THREAD

**Issue by ElianoMarques** [ropensci/plotly#536] opened 2016-04-02 17:53 UTC
Hi, 

I've done a simple bar chart via ggplot2. Everything works fine but the position of the xlab hides half of the lab title. I've tried many different approaches via the element_text but didn't had any luck. 

See the attached the photo to see if you can help. 

<img width="659" alt="screen shot 2016-04-02 at 18 47 30" src="https://cloud.githubusercontent.com/assets/7281303/14228123/227a77e8-f904-11e5-815f-4134313f75bd.png">

**Comment by ElianoMarques** [comment] 2016-04-02 17:54
Count Alerts is partially hidden as you can see in the image.

**Comment by cpsievert** [comment] 2016-05-05 05:59
Duplicate of #510

**Closed by cpsievert** 2016-05-05 05:59 UTC
