### ISSUE TITLE
geom_GeomCustomAnn() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by jonovik** [ropensci/plotly#969] opened 2017-04-23 13:55 UTC
I superimpose a circle on my ggplot using [annotation_custom](http://ggplot2.tidyverse.org/reference/annotation_custom.html) as described [here](http://stackoverflow.com/questions/6862742/draw-a-circle-with-ggplot2#answer-9847076). It would be nice to see this supported by `ggplotly()`. Here is a small reproducible example.

```R
library(ggplot)
library(plotly)
library(grid)

p1 <- qplot(-2:2, -2:2)
p1
ggplotly(p1)  # Works as expected

p2 <- p1 + annotation_custom(grob=circleGrob(r=unit(1,"npc"), gp=gpar(fill=NA)), xmin=-1, xmax=1, ymin=-1, ymax=1)
p2            # Overlays a circle on the plot
ggplotly(p2)  # Does not display the circle

## Warning message:
##   In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
##   geom_GeomCustomAnn() has yet to be implemented in plotly.
## If you'd like to see this geom implemented,
##   Please open an issue with your example code at
##   https://github.com/ropensci/plotly/issues
```

**Comment by cpsievert** [comment] 2017-04-23 17:14
Duplicate of #348

**Closed by cpsievert** 2017-04-23 17:14 UTC
