### ISSUE TITLE
annotation_custom() of ggplot yet to be implemented

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [ropensci/plotly#1168] opened 2017-12-20 20:18 UTC
I made an R package which uses ggplot's annotation_custom()  to add a layer bellow the graph, this is the code that makes the figure I am talking about

`if (!require("SpatialBall")) install.packages("SpatialBall")
library(SpatialBall)`

then:
Get the data
```r
data("season2017")
```
Plot the data 

```r
GSW <- OffShotSeasonGraphTeam(season2017, team = "GSW")
GSW
```

but when I try to use gglpotly on that:

```r
if (!require("plotly")) install.packages("plotly")
library(plotly)
ggplotly(GSW)
```
The court does not show due to the non implementation of the annotation_custom()  function

**Comment by cpsievert** [comment] 2017-12-20 20:22
Duplicate of #348

**Closed by cpsievert** 2017-12-20 20:22 UTC
