### ISSUE TITLE
request to implement geom_GeomTextGGtree() in plotly

### ISSUE THREAD

**Issue by schultzm** [ropensci/plotly#757] opened 2016-10-11 00:23 UTC
Hi, 
 
When running 
```
t <- ggtree(tre) + geom_tiplab()
ggplotly(t)
```
 I get the message 
```
Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomTextGGtree() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```

I would like to display tip labels and tip points etc in plotly for object of class phylo.  

Thanks for the amazing software! 

Mark

**Comment by cpsievert** [comment] 2016-10-12 15:03
duplicate of #566

**Closed by cpsievert** 2016-10-12 15:03 UTC
