### ISSUE TITLE
geom_text_repel from ggrepel package is not supported by Plotly yet

### ISSUE THREAD

**Issue by shrikantsoni88** [ropensci/plotly#1626] opened 2019-09-25 16:08 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the community forum <http://community.plot.ly/c/api/r> or stackoverflow <http://stackoverflow.com>.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/tidyverse/reprex#readme>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---

Brief description of the problem

Hi, I am trying to repel the geom_text point values in plotly, by using the ggplotly function, however it says that geom_text_repel is currently not supported by Plotly yet. This is the exact error given

Warning in geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomTextRepel() has yet to be implemented in plotly.

It will be super helpful if geom_text_repel from the ggrepel package is supported by plotly soon

```r
# insert reprex here
```

**Comment by cpsievert** [comment] 2019-09-25 16:44
Duplicate of #566

**Closed by cpsievert** 2019-09-25 16:44 UTC

**Comment by gforg34** [comment] 2022-10-07 13:27
I have the same issue and I do not know if there is an alternative on that. I want to build an interactive phylogenetic tree in R Shiny , but there is no way to repel the labels. Is there any update on this matter?
