### ISSUE TITLE
feature request: when downloading plot as png using the modebar button, use the current size of the plot as the size of the png.

### ISSUE THREAD

**Issue by finger563** [ropensci/plotly#935] opened 2017-04-10 17:57 UTC
Currently it does not use the size of the plot as it has been rendered into the browser.  The data ranges and such are all the same, but since the size is different the legend may overlap parts that it did not when viewed in the browser and the aspect ratio may be different.

**Comment by cpsievert** [comment] 2017-04-12 03:51
Duplicate of https://github.com/plotly/plotly.js/issues/1576

You should be able to replicate the workaround with a combination of `config()` and `htmlwidgets::JS()`

**Comment by cpsievert** [comment] 2017-04-21 19:20
Closing since I won't be making any changes in the R package to address this

**Closed by cpsievert** 2017-04-21 19:20 UTC
Labels: duplicate
