### ISSUE TITLE
geom_GeomLogticks() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by dewittpe** [ropensci/plotly#1146] opened 2017-11-02 15:57 UTC
This issue is an addendum to issue #1145.

```r
library(ggplot2) # version 2.2.1
library(plotly)  # version 4.7.1

g <-
  ggplot(txhousing) +
  aes(x = date, y = log10(volume)) +
  geom_point() +
  scale_y_continuous(labels = scales::math_format(10^.x)) +
  annotation_logticks(side = "l")
ggplotly(g)

## Warning message:
## In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
##   geom_GeomLogticks() has yet to be implemented in plotly.
##   If you'd like to see this geom implemented,
##   Please open an issue with your example code at
##   https://github.com/ropensci/plotly/issues
````

**Comment by cpsievert** [comment] 2017-12-06 16:25
Duplicate of #348

**Closed by cpsievert** 2017-12-06 16:25 UTC
