### ISSUE TITLE
geom_GeomLogticks() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by Taimin** [ropensci/plotly#1728] opened 2020-03-29 14:58 UTC
---

geom_GeomLogticks() has yet to be implemented in plotly. When I try to render a ggplot object with annotation logticks on the left side of the coordination axis to an interactive plotly object, the log tick didn't show on the plot. Overall it is fine because the interactive plotly plot is still on log scale. However, it would be better to show the log ticks.

**Comment by cpsievert** [comment] 2020-03-30 14:09
Duplicate of #348

**Closed by cpsievert** 2020-03-30 14:09 UTC
