### ISSUE TITLE
Implement geom_dl from directlabels package in R

### ISSUE THREAD

**Issue by humanpowered** [ropensci/plotly#1463] opened 2019-02-12 17:55 UTC
I would like to see the geom_dl function implemented within ggplotly.  This function allows excellent control over where data labels are placed within a plot.

```r
library(plotly)
library(directlabels)


trace_0 <- rnorm(100, mean = 5)
trace_1 <- rnorm(100, mean = 0)
trace_2 <- rnorm(100, mean = -5)
x <- c(1:100)

data <- data.frame(x, trace_0, trace_1, trace_2)
datam <- melt(data, id.vars = 'x', variable.name = 'trace', value.name = 'metric')


p <- ggplot(data = datam, aes(x = x, y = metric, color = trace)) +
  geom_point() +
  theme(legend.position = 'none',
        plot.margin = unit(c(0,2,0,0), units = 'cm')) +
  geom_dl(aes(label = trace), method = list("last.bumpup", cex = 0.7)) +
  geom_smooth(method = 'loess', se = F)
p2 <- ggplotly(p2)
```

**Comment by cpsievert** [comment] 2019-02-16 00:10
Duly noted, but duplicate of #566

**Closed by cpsievert** 2019-02-16 00:10 UTC
