### ISSUE TITLE
Pie Chart Margins seems hard-coded in plotly 4.6 (CRAN version)

### ISSUE THREAD

**Issue by nikhilchoudhry** [ropensci/plotly#1015] opened 2017-05-18 12:36 UTC
Hi,

I am using plotly R library to create pie charts and in the latest CRAN version 4.6 it seems there is some default hardcoded margins, padding added to it. I am not able to override the margins, padding through layout configuration also :

Example :

```r
USPersonalExpenditure <- data.frame("Categorie"=rownames(USPersonalExpenditure), USPersonalExpenditure)
data <- USPersonalExpenditure[,c('Categorie', 'X1960')]
plot_ly(data, labels = ~Categorie, values = ~X1960, type = 'pie') %>%
layout(title = 'United States Personal Expenditures by Categories in 1960')
```

The above code is making pie chart without any padding or margins in plotly 4.5.6 but in 4.6 there is a default margin, padding added to it.

I tried to remove the margins but it doesn't seem to have any effect :

```r
plot_ly(data, labels = ~Categorie, values = ~X1960, type = 'pie') %>%
layout(title = 'Tes Graph', margin = list(t = 0, b = 0, l = 0, r = 0, pad = 0))
```

Can you please help me if I am missing something? Its spoiling the formating of my report which was perfect with version 4.5.6

**Comment by cpsievert** [comment] 2017-05-19 00:25
Duplicate of #1002

**Closed by cpsievert** 2017-05-19 00:25 UTC
