### ISSUE TITLE
Legend title not shown in horizontal orientation

### ISSUE THREAD

**Issue by richierocks** [ropensci/plotly#1704] opened 2020-02-21 18:42 UTC
The legend title is not shown for legends in horizontal orientation.

Here's a line plot with a legend.

```r
library(ggplot2)
library(plotly)

plt <- ggplot(Orange, aes(age, circumference, group = Tree, color = Tree)) + 
  geom_line()
```

The plotly version with a vertical legend correctly displays the title.

```r
ggplotly(plt)
```

![Screenshot 2020-02-21 13 37 33](https://user-images.githubusercontent.com/197589/75061739-52992680-54af-11ea-9224-6ee36c5ed9f2.png)

If I change to horizontal orientation, the title is no longer present

```r
ggplotly(plt) %>% 
  layout(
    legend = list(
      orientation = "h"
    )
  )
```

Notice that the word "Tree" is not present in this image.

![Screenshot 2020-02-21 13 38 53](https://user-images.githubusercontent.com/197589/75061829-8b390000-54af-11ea-99ad-9bdd7c6b3ed8.png)

This is a low priority bug since there is a workaround: you can manually specify the legend title.

```r
ggplotly(plt) %>% 
  layout(
    legend = list(
      orientation = "h", 
      title = list(text = "Tree")
    )
  )
```

![Screenshot 2020-02-21 13 42 07](https://user-images.githubusercontent.com/197589/75062037-f71b6880-54af-11ea-8f89-4aabd9e8a9f6.png)

**Comment by cpsievert** [comment] 2020-02-24 15:29
Duplicate of https://github.com/ropensci/plotly/issues/1049 (there's a WIP https://github.com/ropensci/plotly/pull/1697)

**Closed by cpsievert** 2020-02-24 15:29 UTC
