### ISSUE TITLE
Can't scroll legend on mobile device

### ISSUE THREAD

**Issue by vacon04** [ropensci/plotly#1592] opened 2019-08-07 01:24 UTC
As stated, it is not possible right now (at least for me) to scroll the legend when viewing it from a mobile device.

I have 20 legend items, which can't be displayed without scrolling, but the scroll bar doesn't move, just the rest of the site where the chart is at.

The chart itself is a regular scatter plot with lines, and a range scale slider at the bottom. The y-axis is set to fixedrange = FALSE in order to allow me to zoom vertically on the chart as well.

I am using version 4.9.0.9000 with RStudio and R 3.5.3

**Comment by cpsievert** [comment] 2019-08-12 15:32
Duplicate of https://github.com/plotly/plotly.js/issues/3801

**Closed by cpsievert** 2019-08-12 15:32 UTC
