### ISSUE TITLE
ggplot scale fill interactions

### ISSUE THREAD

**Issue by cbraun7** [ropensci/plotly#283] opened 2015-09-20 01:32 UTC
Lots of problems with this ggplot and plotly. Don't even know where to start to fix them all. Any suggestions...?

Here is the code:

        p <- ggplot() + 

	geom_bar(
			data = data2013, 
			aes(x = factor(education), y =value, fill = interaction(variable,sex), group = sex), 
			stat = 'identity', position = position_dodge()) + 
	
	labs(
			title = "", 
			x  = "", 
		 	y = "Average Monthly Earning", 
		 	colour = "black") + 
	
	theme(
			axis.text.x = element_text(angle = 45, hjust = 1), 
			panel.grid.major = element_line(colour = "grey90"),
			panel.grid.minor = element_line(colour = "grey90"), 
			panel.background = element_rect(fill = "white"), 
			axis.text= element_text(colour = "black"), 
			legend.position = 'bottom', 
			legend.title = element_blank(),
			strip.text.x = element_text(size = 7),
			strip.background = element_rect(fill = 'grey90'))+ 
	
	scale_fill_manual(
			values = c('mediumorchid2','mediumorchid4','steelblue2','steelblue4'),
			labels = c('Female All Employees','Female New Hires','Male All Employees','Male New Hires'))+
	
	facet_wrap(~ind,nrow = 1)

printing in R give:
![screen shot 2015-09-19 at 6 30 04 pm](https://cloud.githubusercontent.com/assets/14366102/9978772/7d2a6ede-5efc-11e5-9ae1-b39b7e4a5bf4.png)

Then ggplotly(p) give:
![screen shot 2015-09-19 at 6 27 04 pm](https://cloud.githubusercontent.com/assets/14366102/9978776/acefbde0-5efc-11e5-9473-a7132aad8f1e.png)

**Comment by cpsievert** [comment] 2015-12-29 16:16
The redundant legend entries is a duplicate of #378. It's also [documented that plotlyjs doesn't yet support horizontal legend entries](https://github.com/ropensci/plotly/wiki/Unsupported-plotly.js-features)

**Closed by cpsievert** 2015-12-29 16:16 UTC
