### ISSUE TITLE
ggplotly does not support negative values

### ISSUE THREAD

**Issue by mubashirqasim** [ropensci/plotly#874] opened 2017-02-07 04:17 UTC
Hi there,

I have just found that ggplotly take absolution of values before plotting. In other words it seems it does not support negative values.

p <- ggplot(dft, aes(x=id, y=value, fill=value)) + geom_bar(stat="identity") +
  geom_abline(intercept = x, slope = 0, color = "blue", size = .3) +
  geom_text(aes(15,x,label = "Avg. value", vjust = -1))

plot(p)
ggplotly(p)

**Comment by tjbutler** [comment] 2017-03-09 21:30
I believe I found the same thing. I have a histogram with different values below and above the horizontal axis. This plots correctly without plotly, with one histogram downward from the horizontal axis and one above it, but with ggplotly it overlays the two histograms on top of each other, both above the axis.

`set.seed(15)
dd<-data.frame(x=rnorm(100,5,2))
set.seed(5)
dd2<-data.frame(x=rnorm(100,5,2))
p3 <- ggplot() + geom_histogram(data=dd,aes(x=x,y=..count..)) + geom_histogram(data=dd2,aes(x=x,y=-..count..),color='green')
p3
ggplotly(p3)
`
![orig_histogram](https://cloud.githubusercontent.com/assets/2529113/23771460/0f480008-04e5-11e7-82d0-aed9c7fb0f61.png)
![plotly_histogram](https://cloud.githubusercontent.com/assets/2529113/23771613/a477e5da-04e5-11e7-99c5-2c693bdbe147.png)

**Comment by maxheld83** [comment] 2017-04-04 18:16
I, too, have this issue. I think it is a duplicate of https://github.com/ropensci/plotly/issues/560

**Comment by rosseji** [comment] 2017-08-25 03:24
Is this not closed because the fix hasn't worked properly? Still getting errors in `plotly_4.7.1`

![screen shot 2017-08-25 at 1 23 31 pm](https://user-images.githubusercontent.com/21113591/29698413-a1eb6dd6-8998-11e7-97a6-ec0a56146e74.png)

**Comment by cpsievert** [comment] 2019-01-24 23:45
This seems to be fixed now

**Closed by cpsievert** 2019-01-24 23:45 UTC
Labels: bug, ggplotly
