### ISSUE TITLE
ggplotly / barplot : Error in if (is.character(new.mode) && !is.na(new.mode))

### ISSUE THREAD

**Issue by giacomovagni** [ropensci/plotly#250] opened 2015-08-11 12:06 UTC
I am trying to plot a simple `barplot` with `ggplot` and `ggplotly` but I get this message error 

`Error in if (is.character(new.mode) && !is.na(new.mode)) { : 
  missing value where TRUE/FALSE needed` 

I have no idea how to solve this issue. 

Here is my ggplot code 
a. 
`dta2 <- dta %>% melt %>%  group_by(Var2, value) %>% summarise(count = n( )/nrow(dta))`
b. 
`ggplot(dta2, aes(x = Var2, y = as.numeric(count), fill = factor(value))) + scale_fill_manual(values=rainbow(20)) + geom_bar(stat='identity', width = 1, position = "stack") + theme_minimal()` 
c. 
`ggplotly()`

`Error in if (is.character(new.mode) && !is.na(new.mode)) { : 
  missing value where TRUE/FALSE needed`

![barplotggplot](https://cloud.githubusercontent.com/assets/6051742/9197065/03828ce8-4029-11e5-8e86-6d2d875efaad.jpeg)

Any idea ? 

Here is my reproductible data 

`dta = structure(c(7L, 2L, 6L, 48L, 56L, 7L, 7L, 7L, 46L, 7L, 7L, 24L, 
7L, 19L, 7L, 30L, 7L, 24L, 42L, 67L, 7L, 2L, 27L, 48L, 56L, 7L, 
7L, 7L, 67L, 7L, 7L, 24L, 7L, 20L, 7L, 30L, 7L, 67L, 42L, 23L, 
7L, 2L, 27L, 48L, 56L, 7L, 7L, 7L, 67L, 7L, 7L, 24L, 7L, 20L, 
7L, 30L, 7L, 67L, 42L, 23L, 7L, 2L, 27L, 48L, 56L, 7L, 7L, 7L, 
67L, 7L, 7L, 24L, 7L, 20L, 7L, 30L, 7L, 67L, 42L, 23L, 7L, 2L, 
27L, 48L, 56L, 7L, 7L, 7L, 67L, 7L, 7L, 24L, 7L, 20L, 7L, 30L, 
7L, 67L, 42L, 23L, 7L, 2L, 27L, 48L, 56L, 7L, 7L, 7L, 67L, 7L, 
7L, 24L, 7L, 20L, 7L, 30L, 7L, 67L, 42L, 23L, 7L, 2L, 27L, 48L, 
56L, 7L, 7L, 7L, 67L, 7L, 7L, 24L, 7L, 20L, 7L, 30L, 7L, 67L, 
42L, 23L, 7L, 2L, 27L, 48L, 56L, 7L, 7L, 7L, 67L, 7L, 7L, 24L, 
7L, 20L, 7L, 30L, 7L, 67L, 42L, 23L, 7L, 2L, 27L, 48L, 56L, 7L, 
7L, 7L, 67L, 7L, 7L, 24L, 7L, 20L, 7L, 30L, 7L, 67L, 42L, 23L, 
7L, 2L, 27L, 48L, 56L, 7L, 7L, 7L, 67L, 7L, 7L, 24L, 7L, 20L, 
7L, 30L, 7L, 67L, 42L, 23L), .Dim = c(20L, 10L), .Dimnames = list(
    c("1013662", "1024583", "1024812", "1025491", "1036642", 
    "1037551", "1037552", "1037991", "1037992", "1040291", "1040292", 
    "1041101", "1041212", "1041651", "104221", "104222", "104331", 
    "104332", "104992", "1052571"), c("400", "401", "402", "403", 
    "404", "405", "406", "407", "408", "409")))`

**Comment by 13bzhang** [comment] 2015-08-11 20:52
Thanks for letting us know. I am looking into this.

**Comment by 13bzhang** [comment] 2015-08-18 03:08
I have been trying to debug this. The error happens when the count variable is not unique within a group. For instance:

```r
# problem
testd <- data.frame(group1 = rep(1:3, each = 3),
                    group2 = LETTERS[1:3],
                    count = c(0.2, 0.2, 0.6)) # We have two 0.2 within each group.
p1 <- ggplot(testd, aes(x = factor(group1), y = count, 
                       fill = factor(group2))) + 
  geom_bar(stat='identity', width = 1, position = "stack")
ggplotly(p1)
```
This produces the error: 

```
Error in if (is.character(new.mode) && !is.na(new.mode)) { : 
  missing value where TRUE/FALSE needed
```
In contrast, 
```r
# not a problem
testd <- data.frame(group1 = rep(1:3, each = 3),
                    group2 = LETTERS[1:3],
                    count = c(0.2, 0.1, 0.6))
p2 <- ggplot(testd, aes(x = factor(group1), y = count, 
                       fill = factor(group2))) + 
  geom_bar(stat='identity', width = 1, position = "stack")
ggplotly(p2)
```
produces the Plotly plot correctly:
https://plot.ly/~13bzhang/1444/count-vs-factorgroup1/

@cpsievert Could this be due to ggplotly's handling of stack?

**Comment by giacomovagni** [comment] 2015-08-18 10:03
Thank you for your answer. I hope we can find a solution.

**Comment by cpsievert** [comment] 2015-08-18 17:48
@13bzhang I have a vague idea of what's causing the problem. I think it has to do with some code I wrote a while back, so I'll plan on taking care of this (I might include it in #264 if it makes sense).

**Comment by hpneverback** [comment] 2015-08-30 16:07
I have experience the same issue, thanks for finding the root cause @13bzhang , hope it will be fixed soon.

**Closed** 2015-12-11 21:36 UTC
