### ISSUE TITLE
renderPlotly pie chart issue

### ISSUE THREAD

**Issue by dipenpatel235** [ropensci/plotly#855] opened 2017-01-23 17:05 UTC
see below code ..
in that i am trying to on hover event get data in renderPrint but get error  **Error: x must be length 1 or 2**  

```
library(shiny)
library(DBI)
library(knitr)
library(pool)
library(plotrix)
library(RColorBrewer)
library(RMySQL)
library(shiny)
library(plotly)
library(ggplot2)
library(dplyr)

ui <- fluidPage(
  plotlyOutput("plot"),
  verbatimTextOutput("event")
)

server <- function(input, output) {
  output$plot <- renderPlotly({
    df <- data.frame(
      group = c("Male", "Female", "Child"),
      value = c(25, 25, 50)
    )
    head(df)
  p <- ggplot(df, aes(x=1, y=value, fill=group)) +
      ggtitle("How I've spent my PhD hours this week") +
      coord_polar(theta='y')
    p <- p +
      geom_bar(stat="identity", color='black') +
      guides(fill=guide_legend(override.aes=list(colour=NA)))
    p
  })
  output$event <- renderPrint({
    d <- event_data("plotly_hover")
    if (is.null(d)) "Hover on a point!" else d
  })
}
shinyApp(ui, server)
```

**Comment by cpsievert** [comment] 2017-03-10 17:26
`coord_polar()` isn't (yet) supported. Duplicate of #878.

**Closed by cpsievert** 2017-03-10 17:26 UTC

**Comment by IrelCM** [comment] 2025-03-14 08:45
Hello, 
I'm trying to use ggploty to my coord_polar() but I get this error: Error in rng[[xy]]$get_labels() : attempt to apply non-function

:'(
